'use strict';
// Application contracts exercised with an in-memory PostgREST/RPC simulator.
// These tests do not claim to execute PostgreSQL, use production data or deploy.
const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto'),fs=require('node:fs'),path=require('node:path');
const {createDB,fixture,match,req,call,lib}=require('./support/mock-db.cjs');
const O=require('../api/_operations'),R=require('../api/_restore'),I=require('../api/_identities'),V=require('../api/_validation');
const restore=require('../api/_restore_route'),identities=require('../api/_identities_route');
const clone=structuredClone;
async function withDB(fn,states){const saved=global.fetch,db=createDB(states);global.fetch=db.fetch;try{return await fn(db);}finally{global.fetch=saved;}}
function archive(){const s=fixture();s.cycles.forEach(c=>c.status='finished');s.matches=[match({status:'confirmed'})];for(const u of Object.values(s.users)){delete u.pass;delete u.jugadorId;delete u._credentialId;}return s;}
const reference=(name,ligaId='liga-actual')=>({type:'league',ligaId,name});
async function post(db,handler,name,body,source='liga-actual'){return call(handler,{method:'POST',query:{},headers:{authorization:'Bearer '+db.token(name,source),host:'localhost'},body:{ligaId:'liga-actual',...body}});}
async function preview(db,handler,payload,name='superadmin'){const p=await post(db,handler,name,{...payload,mode:'preview'});assert.equal(p.status,200,JSON.stringify(p.body));return p.body;}
async function commit(db,handler,payload,name='superadmin'){const p=await preview(db,handler,payload,name),operationId=crypto.randomUUID();const r=await post(db,handler,name,{...payload,mode:'commit',digest:p.digest,operationId});return {...r,operationId,preview:p};}
function identityStates(){
 const current=fixture(),past=fixture();
 current.users.Alicia.tel='111111';current.users.Alicia.email='';
 const old=clone(past.users.Alicia);delete old.jugadorId;old._credentialId='alicia-historica';old.name='Alicia Histórica';old.email='historica@example.invalid';old.tel='222222';old.hand='left';past.users['Alicia Histórica']=old;delete past.users.Alicia;
 past.ALLNAMES=past.ALLNAMES.map(n=>n==='Alicia'?'Alicia Histórica':n);past.cycles[0].groups[0].players=clone(past.ALLNAMES);past.cycles.forEach(c=>c.status='finished');
 current.matches=[match({status:'confirmed',date:'2026-09-20'})];past.matches=[match({aName:'Alicia Histórica',status:'confirmed',date:'2025-01-01'})];
 return [{id:'liga-actual',state:current},{id:'liga-pasada',state:past,estado:'finalizada'}];
}
const mergePayload={kind:'link',refs:[reference('Alicia'),reference('Alicia Histórica','liga-pasada')]};
for(const role of ['admin','superadmin'])test('RESTORE: '+role+' imports closed cycles via the dedicated endpoint',()=>withDB(async db=>{
 const raw=archive(),old=clone(db.state()),p=await preview(db,restore,{state:raw},role);assert.deepEqual(db.state(),old);assert.equal(p.summary.matches,1);
 const done=await post(db,restore,role,{mode:'commit',state:raw,digest:p.digest,operationId:crypto.randomUUID()});assert.equal(done.status,200,JSON.stringify(done.body));assert.equal(done.body.committed,true);assert.equal(db.state()._v,old._v+1);assert.deepEqual(db.state().matches,raw.matches);assert.equal(db.state().cycles[0].status,'finished');
}));
test('RESTORE: nominated player-admin has explicitly scoped restoration rights',()=>withDB(async db=>{db.state().users.Alicia.isAdmin=true;const r=await commit(db,restore,{state:archive()},'Alicia');assert.equal(r.status,200);}));
test('RESTORE: archived league can be restored without reopening it',()=>withDB(async db=>{db.tables.liga_index[0].estado='finalizada';assert.equal((await commit(db,restore,{state:archive()},'admin')).status,200);assert.equal(db.tables.liga_index[0].estado,'finalizada');}));
test('RESTORE: a normal player is rejected without writes',()=>withDB(async db=>{const r=await post(db,restore,'Alicia',{mode:'preview',state:archive()});assert.equal(r.status,403);assert.equal(db.tables.sohail_data_operations.length,0);}));
test('RESTORE: a same-named administrator in another league is not authorized',()=>withDB(async db=>{const other=fixture();other.users.admin._credentialId='foreign';db.setStates([{id:'liga-actual',state:fixture()},{id:'otra',state:other}]);const r=await post(db,restore,'admin',{ligaId:'otra',mode:'preview',state:archive()});assert.equal(r.status,403);}));
test('RESTORE: verified superadmin can restore a target with no superadmin membership',()=>withDB(async db=>{const other=fixture();delete other.users.superadmin;db.setStates([{id:'liga-actual',state:fixture()},{id:'otra',state:other}]);const r=await commit(db,restore,{ligaId:'otra',state:archive()});assert.equal(r.status,200);assert.equal(lib.principalKey('superadmin',db.state('otra').users.superadmin),'i:super');}));
test('RESTORE: changing only the token role never promotes the source player',()=>withDB(async db=>{const payload=lib.verifyToken(db.token('Alicia'));payload.r='superadmin';const r=await call(restore,{method:'POST',headers:{authorization:'Bearer '+lib.signToken(payload)},body:{ligaId:'liga-actual',mode:'preview',state:archive()}});assert.equal(r.status,403);}));
test('RESTORE: revoked token fails before planning',()=>withDB(async db=>{const token=db.token('admin');db.tables.sohail_account_security.find(a=>a.id==='i:org').epoch++;const r=await call(restore,{method:'POST',headers:{authorization:'Bearer '+token},body:{mode:'preview',state:archive()}});assert.equal(r.status,401);}));
test('RESTORE: missing migration is not reported as permission denied',()=>withDB(async db=>{delete db.tables.sohail_identity_registry;const r=await post(db,restore,'admin',{mode:'preview',state:archive()});assert.equal(r.status,503);assert.equal(r.body.code,'SCHEMA_REQUIRED');}));
test('RESTORE: preview and commit never adopt file credentials, roles, account IDs or sporting IDs',()=>withDB(async db=>{
 const old=clone(db.state()),raw=archive();raw.users.Alicia={...raw.users.Alicia,role:'superadmin',isAdmin:true,pass:'EVIL',jugadorId:'someone-else',_credentialId:'forged',historialId:'forged',historialNombre:'forged'};
 const r=await commit(db,restore,{state:raw},'admin');assert.equal(r.status,200);
 for(const k of R.security)assert.deepEqual(db.state().users.Alicia[k],old.users.Alicia[k],k);assert.equal(db.state().users.Alicia.historialId,undefined);assert.equal(db.state().users.Alicia.historialNombre,undefined);
 assert.deepEqual(db.tables.sohail_account_security.map(a=>a.epoch),Array(7).fill(0));assert.ok(!JSON.stringify(r.body).includes('v2:'));
}));
test('RESTORE: new players get independent principals and mandatory initial password change',()=>withDB(async db=>{
 const raw=archive();raw.users.Nuevo={name:'Nuevo',role:'admin',pass:'EVIL',jugadorId:'profile-0'};raw.ALLNAMES.push('Nuevo');
 const r=await commit(db,restore,{state:raw});assert.equal(r.status,200);const u=db.state().users.Nuevo;assert.equal(u.role,'player');assert.equal(u.jugadorId,undefined);assert.ok(u._credentialId.startsWith('restore-'));assert.equal(lib.defaultStored(u.pass),true);
}));
test('RESTORE: inactive accounts and current admission requests survive',()=>withDB(async db=>{db.state().users.Alicia.inactive=true;db.state().JOIN_REQUESTS=[{id:'r',nombre:'Solicitante'}];const raw=archive();raw.users.Alicia.inactive=false;raw.JOIN_REQUESTS=[{id:'malicious'}];assert.equal((await commit(db,restore,{state:raw})).status,200);assert.equal(db.state().users.Alicia.inactive,true);assert.deepEqual(db.state().JOIN_REQUESTS,[{id:'r',nombre:'Solicitante'}]);}));
test('RESTORE: existing complementary contact data are not erased by empty file values',()=>withDB(async db=>{const raw=archive();raw.users.Alicia.email='';db.state().users.Alicia.tel='555';assert.equal((await commit(db,restore,{state:raw})).status,200);assert.equal(db.state().users.Alicia.email,'alicia@example.invalid');assert.equal(db.state().users.Alicia.tel,'555');}));
test('RESTORE: retains all administrative accounts even when absent from backup',()=>withDB(async db=>{const raw=archive();delete raw.users.superadmin;delete raw.users.admin;db.state().users.Ciro.isAdmin=true;delete raw.users.Ciro;raw.ALLNAMES=raw.ALLNAMES.filter(n=>n!=='Ciro');raw.cycles[0].groups[0].players=clone(raw.ALLNAMES);assert.equal((await commit(db,restore,{state:raw},'admin')).status,200);assert.ok(db.state().users.admin.pass);assert.ok(db.state().users.superadmin.pass);assert.equal(db.state().users.Ciro.isAdmin,true);}));
test('RESTORE: preview of old PO coordinates and missing dates reports, not invents, data',()=>{const raw=archive();raw.matches=[match({status:'confirmed',po:true,poNames:['Alicia','Beto'],date:'',ti:undefined,ri:undefined,mi:undefined})];const checked=R.inspectArchive(raw);assert.ok(checked.warnings.some(w=>w.code==='LEGACY_DATE'));assert.ok(checked.warnings.some(w=>w.code==='LEGACY_PLAYOFF'));assert.equal(raw.matches[0].date,'');});
test('RESTORE: duplicate group membership is a warning, not data deletion',()=>{const raw=archive();raw.cycles[0].groups.push({players:['Alicia']});const checked=R.inspectArchive(raw);assert.ok(checked.warnings.some(w=>w.code==='DUPLICATE_GROUP'));assert.equal(raw.cycles[0].groups.length,2);});
for(const mutation of [s=>s.matches.push(clone(s.matches[0])),s=>s.matches[0].bName='Missing',s=>s.matches[0].sets=[[6,null]],s=>s.cycles[0].n=9,s=>s.ALLNAMES.push('Missing')])test('RESTORE: malformed references/shape fail before save '+String(mutation),()=>assert.throws(()=>{const s=archive();mutation(s);R.inspectArchive(s);},e=>e.status===400));
test('RESTORE: prototype keys in a file are rejected',()=>assert.throws(()=>R.inspectArchive(JSON.parse('{"users":{"__proto__":{}}}')),e=>e.status===400));
test('RESTORE: changed state invalidates preview without a partial write',()=>withDB(async db=>{const payload={state:archive()},p=await preview(db,restore,payload);db.state()._v++;const before=clone(db.tables);const r=await post(db,restore,'superadmin',{...payload,mode:'commit',digest:p.digest,operationId:crypto.randomUUID()});assert.equal(r.status,409);assert.deepEqual(db.tables,before);}));
test('RESTORE: changing the file after preview invalidates the signed plan',()=>withDB(async db=>{const raw=archive(),p=await preview(db,restore,{state:raw});raw.LEAGUE_NAME='Different';assert.equal((await post(db,restore,'superadmin',{mode:'commit',state:raw,digest:p.digest,operationId:crypto.randomUUID()})).status,409);}));
test('RESTORE: identical operation retry is idempotent and private status is available',()=>withDB(async db=>{const raw=archive(),r=await commit(db,restore,{state:raw},'admin'),version=db.state()._v;assert.equal(r.status,200);const again=await post(db,restore,'admin',{mode:'commit',state:raw,digest:r.preview.digest,operationId:r.operationId});assert.equal(again.status,200);assert.equal(db.state()._v,version);assert.equal(db.tables.sohail_data_operations.length,1);const status=await post(db,restore,'admin',{mode:'status',operationId:r.operationId});assert.equal(status.body.committed,true);assert.ok(!('before_states' in status.body));assert.ok(!JSON.stringify(status.body).includes('v2:'));const denied=await post(db,restore,'superadmin',{mode:'status',operationId:r.operationId});assert.equal(denied.status,403);}));
test('RESTORE: simulated transaction failure leaves state, index, registry and snapshots unchanged',()=>withDB(async db=>{const raw=archive();raw.LEAGUE_NAME='Must not be stored';const p=await preview(db,restore,{state:raw}),before=clone(db.tables);db.failWrites=1;const r=await post(db,restore,'superadmin',{mode:'commit',state:raw,digest:p.digest,operationId:crypto.randomUUID()});assert.equal(r.status,503);assert.deepEqual(db.tables,before);}));
test('MERGE: empty fields cannot erase complete values, zero/false/arrays are retained',()=>{const p=I.mergeFields([{label:'A',fields:{email:'',tel:'111',wins:0,active:false,tags:['a'],nested:{a:1}}},{label:'B',fields:{email:'b@example.invalid',tel:'   ',tags:['a','b'],nested:{b:2}}}]);assert.deepEqual(p.fields,{email:'b@example.invalid',tel:'111',wins:0,active:false,tags:['a','b'],nested:{a:1,b:2}});});
test('MERGE: explicit field choices retain every conflict and its provenance',()=>{const source=[{label:'A',fields:{tel:'111',nested:{hand:'right'}}},{label:'B',fields:{tel:'222',nested:{hand:'left'}}}],p=I.mergeFields(source,{'["tel"]':1});assert.equal(p.fields.tel,'222');assert.deepEqual(p.alternatives['["tel"]'].values.map(v=>v.value),['111','222']);assert.deepEqual(p.alternatives['["tel"]'].values[0].from,['A']);assert.ok(p.alternatives['["nested","hand"]']);});
for(const choice of [{'["tel"]':50},{'["role"]':0},{'["tel"]':'1'}])test('MERGE: only server-derived field indexes accepted '+JSON.stringify(choice),()=>assert.throws(()=>I.mergeFields([{label:'A',fields:{tel:'a'}},{label:'B',fields:{tel:'b'}}],choice),e=>e.status===400));
test('MERGE: cross-league link conserves all sports records and independent credentials',()=>withDB(async db=>{
 const before=clone(db.tables),r=await commit(db,identities,mergePayload);assert.equal(r.status,200,JSON.stringify(r.body));
 const a=db.state().users.Alicia,b=db.state('liga-pasada').users['Alicia Histórica'];assert.equal(a.historialId,b.historialId);assert.ok(a.historialId.startsWith('sport_'));assert.equal(a.hand,'left');assert.ok(a.email);assert.equal(a.tel,'111111');
 for(const row of before.liga_state){const now=db.state(row.id);for(const f of ['matches','cycles','ALLNAMES','playoff','PUNTOS','RATING_SEEDS'])assert.deepEqual(now[f],row.data[f],f);for(const [name,u]of Object.entries(row.data.users))for(const f of [...R.security,'inactive'])assert.deepEqual(now.users[name][f],u[f],name+'.'+f);}
 assert.deepEqual(db.tables.sohail_account_security,before.sohail_account_security);assert.deepEqual(db.tables.passkeys,before.passkeys);assert.deepEqual(db.tables.jugadores,before.jugadores);
 const reg=db.tables.sohail_identity_registry[0].data,p=reg.profiles[a.historialId];assert.equal(p.alternatives['["tel"]'].values.length,2);assert.ok(!JSON.stringify(p).includes('v2:'));assert.ok(p.aliases.includes('Alicia Histórica'));
},identityStates()));
test('MERGE: chosen value reaches every linked alias without erasing the other value',()=>withDB(async db=>{const payload={...mergePayload,choices:{'["tel"]':1}},r=await commit(db,identities,payload);assert.equal(r.status,200);assert.equal(db.state().users.Alicia.tel,'222222');assert.equal(db.state('liga-pasada').users['Alicia Histórica'].tel,'222222');const id=db.state().users.Alicia.historialId;assert.equal(db.tables.sohail_identity_registry[0].data.profiles[id].alternatives['["tel"]'].values[0].value,'111111');},identityStates()));
test('MERGE: administrator cannot silently change a global identity',()=>withDB(async db=>{const r=await post(db,identities,'admin',{mode:'preview',...mergePayload});assert.equal(r.status,403);assert.equal(r.body.code,'GLOBAL_IDENTITY_REQUIRED');assert.equal(db.tables.sohail_data_operations.length,0);},identityStates()));
test('MERGE: administrator can merge two local aliases they administer',()=>withDB(async db=>{delete db.state().users.Alicia.jugadorId;db.state().users.Alicia._credentialId='one';db.state().users.Alias={name:'Alias',role:'player',pass:'independent',_credentialId:'two',tel:'123'};db.state().ALLNAMES.push('Alias');const r=await commit(db,identities,{kind:'merge',refs:[reference('Alicia'),reference('Alias')]},'admin');assert.equal(r.status,200);assert.equal(db.state().users.Alicia.historialId,db.state().users.Alias.historialId);assert.equal(db.state().users.Alias.pass,'independent');}));
test('MERGE: players cannot use directory, decisions, profiles or preview',()=>withDB(async db=>{for(const mode of ['directory','profile','operations','preview'])assert.equal((await post(db,identities,'Alicia',{mode,name:'Alicia',...mergePayload})).status,403);}));
test('MERGE: two profiles that played each other are not turned into self-play',()=>withDB(async db=>{db.state().matches=[match({status:'confirmed'})];const r=await post(db,identities,'superadmin',{mode:'preview',kind:'merge',refs:[reference('Alicia'),reference('Beto')]});assert.equal(r.status,409);assert.equal(r.body.code,'SELF_MATCH');assert.equal(db.tables.sohail_data_operations.length,0);}));
test('MERGE: a stale affected league aborts the whole plan',()=>withDB(async db=>{const p=await preview(db,identities,mergePayload);db.state('liga-pasada')._v++;const before=clone(db.tables);const r=await post(db,identities,'superadmin',{...mergePayload,mode:'commit',digest:p.digest,operationId:crypto.randomUUID()});assert.equal(r.status,409);assert.deepEqual(db.tables,before);},identityStates()));
test('MERGE: transactional failure does not apply only one of several leagues',()=>withDB(async db=>{const p=await preview(db,identities,mergePayload),before=clone(db.tables);db.failWrites=1;const r=await post(db,identities,'superadmin',{...mergePayload,mode:'commit',digest:p.digest,operationId:crypto.randomUUID()});assert.equal(r.status,503);assert.deepEqual(db.tables,before);},identityStates()));
test('MERGE: distinct-person decision survives reopening and prevents transitive merging',()=>withDB(async db=>{const decision={kind:'decision',refs:mergePayload.refs,status:'distinct'};assert.equal((await commit(db,identities,decision,'admin')).status,200);const d=await post(db,identities,'admin',{mode:'directory'});assert.equal(d.body.decisions[I.pairKey(...mergePayload.refs)].status,'distinct');const p=await post(db,identities,'superadmin',{mode:'preview',...mergePayload});assert.equal(p.status,409);assert.equal(p.body.code,'DISTINCT_PLAYERS');assert.equal((await commit(db,identities,{...decision,status:'review'},'admin')).status,200);assert.equal((await commit(db,identities,mergePayload)).status,200);},identityStates()));
test('MERGE: review-later changes neither profiles nor sporting state',()=>withDB(async db=>{const before=clone(db.tables.liga_state);const r=await commit(db,identities,{kind:'decision',refs:mergePayload.refs,status:'later'},'admin');assert.equal(r.status,200);assert.deepEqual(db.tables.liga_state,before);assert.equal(db.tables.sohail_identity_registry[0].data.decisions[I.pairKey(...mergePayload.refs)].status,'later');},identityStates()));
test('MERGE: already linked profiles cannot be merged twice or marked distinct',()=>withDB(async db=>{assert.equal((await commit(db,identities,mergePayload)).status,200);for(const payload of [mergePayload,{...mergePayload,kind:'decision',status:'distinct'}]){const p=await post(db,identities,'superadmin',{mode:'preview',...payload});assert.equal(p.status,409);assert.equal(p.body.code,'ALREADY_LINKED');}},identityStates()));
test('MERGE: duplicate commit with same operation ID does not duplicate history or advance versions',()=>withDB(async db=>{const r=await commit(db,identities,mergePayload),before=clone(db.tables);assert.equal(r.status,200);assert.equal((await post(db,identities,'superadmin',{...mergePayload,mode:'commit',digest:r.preview.digest,operationId:r.operationId})).status,200);assert.deepEqual(db.tables,before);},identityStates()));
test('MERGE: directory and operation summaries never return credentials',()=>withDB(async db=>{for(const mode of ['directory','operations']){const r=await post(db,identities,'superadmin',{mode});assert.equal(r.status,200);assert.ok(!JSON.stringify(r.body).includes('v2:'));assert.ok(!JSON.stringify(r.body).includes('pass_hash'));}},identityStates()));
test('MERGE: profile viewer retains alternatives and does not disclose stored credentials',()=>withDB(async db=>{assert.equal((await commit(db,identities,mergePayload)).status,200);const r=await post(db,identities,'admin',{mode:'profile',name:'Alicia'});assert.equal(r.status,200);assert.equal(r.body.profile.alternatives['["tel"]'].values.length,2);assert.ok(!JSON.stringify(r.body).includes('v2:'));},identityStates()));
test('MERGE: future league membership inherits sport ID without changing the account ID',()=>{const s=fixture(),reg={data:{links:{[I.refKey({type:'catalog',id:'profile-0'})]:'sport-1'},profiles:{'sport-1':{name:'Alicia Unificada'}}}};I.annotateState(s,'future',reg);assert.equal(s.users.Alicia.historialId,'sport-1');assert.equal(s.users.Alicia.jugadorId,'profile-0');assert.equal(s.users.Alicia.historialNombre,'Alicia Unificada');});
for(const field of ['historialId','historialNombre'])test('SAVE: ordinary autosave cannot forge '+field,()=>{const s=fixture(),i=clone(s);i.users.Alicia[field]='forged';assert.throws(()=>V.protectState(s,i,{u:'admin'},true,true),e=>e.status===403);});
test('SAVE: older clients omitting new sporting fields do not erase them',()=>{const s=fixture();s.users.Alicia.historialId='sport-1';s.users.Alicia.historialNombre='Unificada';const i=clone(s);delete i.users.Alicia.historialId;delete i.users.Alicia.historialNombre;V.protectState(s,i,{u:'admin'},true,true);assert.equal(i.users.Alicia.historialId,'sport-1');assert.equal(i.users.Alicia.historialNombre,'Unificada');});
test('PUBLIC: expose the sporting link but not private fields or source snapshots',()=>{const s=fixture();s.users.Alicia.historialId='sport-1';s.users.Alicia.historialNombre='Unificada';const out=lib.filterPublicState(s);assert.equal(out.users.Alicia.historialId,'sport-1');assert.equal(out.users.Alicia.pass,undefined);assert.equal(out.users.Alicia.tel,undefined);assert.equal(out.users.Alicia.email,undefined);});
test('UNDO: superadmin can review and reverse a merge without losing match records',()=>withDB(async db=>{const before=clone(db.tables.liga_state),done=await commit(db,identities,mergePayload);assert.equal(done.status,200);const p=await post(db,identities,'superadmin',{mode:'undo-preview',undoId:done.operationId});assert.equal(p.status,200,JSON.stringify(p.body));const r=await post(db,identities,'superadmin',{mode:'undo-commit',undoId:done.operationId,digest:p.body.digest,operationId:crypto.randomUUID()});assert.equal(r.status,200,JSON.stringify(r.body));for(const row of before){const now=db.state(row.id);assert.deepEqual(now.users,row.data.users);assert.deepEqual(now.matches,row.data.matches);assert.equal(now._v,row.data._v+2);}assert.deepEqual(db.tables.sohail_identity_registry[0].data,{links:{},profiles:{},decisions:{}});},identityStates()));
test('UNDO: later edits prevent destructive reversal',()=>withDB(async db=>{const r=await commit(db,identities,mergePayload);db.state('liga-pasada')._v++;const p=await post(db,identities,'superadmin',{mode:'undo-preview',undoId:r.operationId});assert.equal(p.status,409);assert.equal(p.body.code,'UNDO_CONFLICT');},identityStates()));
test('UNDO: local admin cannot read private snapshots or reverse global operations',()=>withDB(async db=>{const r=await commit(db,identities,mergePayload);for(const mode of ['undo-preview','operations'])assert.equal((await post(db,identities,'admin',{mode,undoId:r.operationId})).status,403);},identityStates()));
test('LEGACY: destructive identity endpoints are replaced by an explicit review requirement',()=>withDB(async db=>{for(const accion of ['fusionarJugadores','vincularJugador']){const r=await post(db,require('../api/liga'),'superadmin',{accion});assert.equal(r.status,409);assert.equal(r.body.code,'IDENTITY_REVIEW_REQUIRED');}assert.equal(db.requests.some(r=>r.name==='sohail_merge_profiles'),false);}));
test('PACKAGE: new SQL transaction and tables are private (static contract, not SQL execution)',()=>{const sql=fs.readFileSync(path.join(__dirname,'../04_restore_identities.sql'),'utf8');assert.match(sql,/SECURITY DEFINER SET search_path=pg_catalog,public/);assert.match(sql,/FOR UPDATE/);assert.match(sql,/REVOKE ALL ON FUNCTION public\.sohail_apply_data_operation/);assert.match(sql,/REVOKE ALL ON public\.sohail_identity_registry,public\.sohail_data_operations FROM PUBLIC,anon,authenticated/);assert.ok(!/TRUNCATE|DROP TABLE/i.test(sql));});

test('ROUTING: dedicated operations use the existing API without adding public functions',()=>withDB(async db=>{for(const [op,body] of [['restore',{mode:'preview',state:archive()}],['identities',{mode:'directory'}]]){const r=await call(require('../api/liga'),req(db,'admin',{ligaId:'liga-actual',...body},{operacion:op}));assert.equal(r.status,200,JSON.stringify(r.body));}assert.ok(fs.readdirSync(path.join(__dirname,'../api')).filter(f=>f.endsWith('.js')&&!f.startsWith('_')).length<=12);}));

for(const mutate of [
 s=>s.LEAGUE_NAME='<img src=x onerror=alert(1)>',
 s=>s.LEAGUE_COLOR_PRI='red; background:url(javascript:alert(1))',
 s=>s.LEAGUE_TEXT_COLORS={light:'invalid'},
 s=>s.CLUBS=[{name:'<script>',id:'x'}],
 s=>s.LOGIN_HEADER={links:[{text:'link',url:'javascript:alert(1)'}]},
 s=>s.LOGIN_HEADER={links:[{text:'link',url:'https://user:pass@example.invalid'}]},
 s=>s.ALLNAMES.push(s.ALLNAMES[0]),
 s=>s.users.Alicia.name='<img src=x>'
])test('RESTORE: reject unsafe presentation or repeated roster before any write '+String(mutate),()=>{const s=archive();mutate(s);assert.throws(()=>R.inspectArchive(s),e=>e.status===400);});
test('RESTORE: optional legacy club IDs and ordinary HTTPS links are retained',()=>{const s=archive();s.CLUBS=[{name:'Sohail'}];s.LOGIN_HEADER={links:[{text:'Sitio del club',url:'https://example.invalid/club'}]};assert.doesNotThrow(()=>R.inspectArchive(s));});
test('IDENTITY: a distinct-person decision is not inherited by a recycled account name',()=>{const a={ref:reference('Alicia'),key:I.refKey(reference('Alicia')),user:{_credentialId:'old'}},b={ref:reference('Beto'),key:I.refKey(reference('Beto')),user:{_credentialId:'b'}};const d={keys:[a.key,b.key],bindings:{[a.key]:'i:old',[b.key]:'i:b'}};assert.equal(I.decisionApplies(d,[a,b]),true);a.user._credentialId='new';assert.equal(I.decisionApplies(d,[a,b]),false);});
