'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const H=require('../public/history-leagues'),D=require('../public/match-history');
const m=(id,a,b,date,extra={})=>({id,aName:a,bName:b,date,status:'confirmed',sets:[[6,3],[6,2]],...extra});
function season(id,name,users,matches,estado='activa'){return {entry:{id,nombre:name,estado},state:{users,matches}};}
const target={name:'Ana Actual',id:'sport_ana'};
const current=()=>season('current','Actual',{'Ana Actual':{historialId:'sport_ana'},'Ana Alias':{historialId:'sport_ana'},'Luis Actual':{historialId:'sport_luis'}},[m(1,'Ana Actual','Luis Actual','2026-09-20'),m(2,'Ana Alias','Luis Actual','2026-09-19')]);
const past=()=>season('past','Pasada',{'Ana Histórica':{historialId:'sport_ana'},'Luis Histórico':{historialId:'sport_luis'}},[m(1,'Ana Histórica','Luis Histórico','2025-01-01',{sets:[[2,6],[2,6]]}),m(3,'Ana Histórica','Luis Histórico','',{po:true,poNames:['Ana Histórica','Luis Histórico'],which:'main'})],'finalizada');
test('HISTORY: current and historical aliases aggregate only via explicit sporting identity',()=>{const c=current(),p=past(),a=H.project(c.state,c.entry,target,{current:true}),b=H.project(p.state,p.entry,target);assert.equal(a.records.length,2);assert.equal(b.records.length,2);assert.equal(a.records[1]._mhSubject,'Ana Alias');assert.equal(b.records[0]._mhSubject,'Ana Histórica');});
test('H2H: match-ID collisions across leagues survive and newest dates precede missing dates',()=>{const c=current(),p=past(),all=[...H.project(c.state,c.entry,target,{current:true}).records,...H.project(p.state,p.entry,target).records];const ctx={id:c.entry.id,users:c.state.users},rival=D.person('Luis Actual',ctx);const h=D.headToHead(all,'Ana Actual',rival.key,ctx);assert.equal(h.list.length,4);assert.equal(new Set(h.list.map(x=>x._mhKey)).size,4);assert.deepEqual(h.list.map(x=>x.date),['2026-09-20','2026-09-19','2025-01-01','']);assert.equal(h.wins,3);assert.equal(h.losses,1);});
test('HISTORY: equal unlinked names remain unresolved rather than guessed',()=>{const p=season('past','Pasada',{'Ana Actual':{},'Luis':{jugadorId:'l'}},[m(1,'Ana Actual','Luis','2020-01-01')],'finalizada');const out=H.project(p.state,p.entry,target);assert.equal(out.records.length,0);assert.ok(out.issues.includes('unlinked'));});
test('HISTORY: equal names with different IDs are separate people',()=>{const p=season('past','Pasada',{'Ana Actual':{historialId:'different'},'Luis':{jugadorId:'l'}},[m(1,'Ana Actual','Luis','2020-01-01')]);assert.equal(H.project(p.state,p.entry,target).records.length,0);});
test('H2H: an opponent lacking a link in another league is not guessed by name',()=>{const ctx={id:'current',users:{Luis:{historialId:'sport_luis'}}},x={...m(1,'Ana Histórica','Luis','2020-01-01'),_mhSubject:'Ana Histórica',_mhLeagueId:'past',_mhPlayerIds:['sport_ana',null]};assert.equal(D.headToHead([x],'Ana Actual',D.person('Luis',ctx).key,ctx).list.length,0);});
test('HISTORY: sporting projection never carries contact fields or authentication data',()=>{const c=current();c.state.users['Ana Actual'].pass='secret';c.state.matches[0].privateField='secret';const out=H.project(c.state,c.entry,target,{current:true});assert.ok(!JSON.stringify(out).includes('secret'));});
test('HISTORY: collector includes active, archived and retained editions without switching sessions',async()=>{const c=current(),p=past(),other=season('other-active','Otra activa',p.state.users,[m(1,'Ana Histórica','Luis Histórico','2026-09-18')]);const requests=[];const fetcher=async(url,op)=>{requests.push({url,op});if(url==='/api/liga'&&JSON.parse(op.body).accion==='listar')return {ok:true,json:async()=>({ligas:[c.entry,p.entry,other.entry]})};if(url==='/api/liga')return {ok:true,json:async()=>({estado:p.state})};return {ok:true,json:async()=>({state:other.state})};};const out=await H.collect({current:{...c.entry,...c.state},name:target.name,token:'local-test',fetcher});assert.equal(out.leagues.length,2);assert.equal(out.records.length,3);assert.ok(requests.every(r=>!r.url.includes('elegir')));assert.ok(requests.some(r=>r.url.includes('historial=1')));});
