'use strict';
// Targeted v3.9 regression: uses no production data and makes no external requests.
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const {createDB,fixture,req,call,lib}=require('./support/mock-db.cjs');
const {protectState}=require('../api/_validation');
function theme(){
 const css={};const document={documentElement:{setAttribute(){},style:{setProperty:(k,v)=>css[k]=v}},dispatchEvent(){}};
 const c={window:{document,localStorage:{getItem(){return null;},setItem(){}},matchMedia:()=>({matches:false,addEventListener(){}})},CustomEvent:function(t,o){this.type=t;}};
 vm.createContext(c);vm.runInContext(fs.readFileSync(path.join(__dirname,'../public/theme.js'),'utf8'),c);return{api:c.window.SohailAppearance,css};
}
test('Text palette: normalises only three explicitly supported fields',()=>{
 const {api}=theme();assert.deepEqual(JSON.parse(JSON.stringify(api.normalizeTextColors({light:'#AbC',dark:'#F3F3F3',header:'#ff0',other:'#fff'}))),{light:'#aabbcc',dark:'#f3f3f3',header:'#ffff00'});
});
for(const val of [null,[],{light:'url(javascript:1)'},{dark:'red'},{header:'#ffffff;display:none'}])test('Text palette ignores unsafe runtime input '+JSON.stringify(val),()=>{assert.equal(Object.keys(theme().api.normalizeTextColors(val)).length,0);});
test('Colourless legacy league retains automatic light and dark defaults',()=>{const {api,css}=theme();api.setTextColors({});assert.equal(css['--text'],'#1b2433');api.setPreference('dark');assert.equal(css['--text'],'#f3f3f3');});
test('Custom text colours are independent for light and dark',()=>{const {api,css}=theme();api.setTextColors({light:'#173c2b',dark:'#d9ffe6'});assert.equal(css['--text'],'#173c2b');api.setPreference('dark');assert.equal(css['--text'],'#d9ffe6');});
test('Header text changes without changing action/semantic colours',()=>{const {api,css}=theme();const action=css['--action'];api.setTextColors({header:'#fff2b1'});assert.equal(css['--brand-ink'],'#fff2b1');assert.equal(css['--action'],action);assert.equal(css['--on-action'],'#ffffff');});
test('Low-contrast stored colours fall back safely',()=>{const {api,css}=theme();api.setTextColors({light:'#ffffff',dark:'#000000',header:'#1b4f9c'});assert.equal(css['--text'],'#1b2433');assert.notEqual(css['--brand-ink'],'#1b4f9c');api.setPreference('dark');assert.equal(css['--text'],'#f3f3f3');});
test('Resetting optional preference removes last league colour',()=>{const {api,css}=theme();api.setTextColors({light:'#163823'});api.setTextColors(undefined);assert.equal(css['--text'],'#1b2433');});
test('Manual text contrast is checked on all neutral surfaces',()=>{const {api}=theme();for(const mode of ['light','dark'])for(const colour of ['#345','#abc','#111111','#eeeeee','#d9ffe6']){const result=api.textPalette(mode,{[mode]:colour},'#bb22aa','#00ffff');for(const bg of result.surfaces)assert.ok(api.contrast(bg,result.main)>=4.5);}});
for(const name of ['admin','superadmin'])test(name+' can save and read per-league text settings with real controller',async()=>{const db=createDB();global.fetch=db.fetch;const s=structuredClone(db.state());s.LEAGUE_TEXT_COLORS={light:'#123456',dark:'#def0ff',header:'#fff2b1'};const r=await call(require('../api/save'),req(db,name,{state:s,ligaId:'liga-actual'}));assert.equal(r.status,200,JSON.stringify(r.body));assert.deepEqual(db.state().LEAGUE_TEXT_COLORS,s.LEAGUE_TEXT_COLORS);});
test('Player cannot change league text through a forged request',async()=>{const db=createDB();global.fetch=db.fetch;const s=structuredClone(db.state());s.LEAGUE_TEXT_COLORS={light:'#123456'};const r=await call(require('../api/save'),req(db,'Alicia',{state:s,ligaId:'liga-actual'}));assert.equal(r.status,403);assert.equal(db.state().LEAGUE_TEXT_COLORS,undefined);});
for(const c of [null,[],{light:'red'},{header:'#fff;position:absolute'},{other:'#123456'},{dark:123}])test('Server rejects invalid preference '+JSON.stringify(c),()=>{const s=fixture(),i=structuredClone(s);i.LEAGUE_TEXT_COLORS=c;assert.throws(()=>protectState(s,i,{u:'admin'},true,true));});
test('Server preserves optional preference from older admin client',()=>{const s=fixture();s.LEAGUE_TEXT_COLORS={dark:'#def0ff'};const i=structuredClone(s);delete i.LEAGUE_TEXT_COLORS;protectState(s,i,{u:'admin'},true,true);assert.deepEqual(i.LEAGUE_TEXT_COLORS,s.LEAGUE_TEXT_COLORS);});
test('Older player client omitting optional preference still cannot remove it',()=>{const s=fixture();s.LEAGUE_TEXT_COLORS={dark:'#def0ff'};const i=structuredClone(s);delete i.LEAGUE_TEXT_COLORS;protectState(s,i,{u:'Alicia'},false,false);assert.deepEqual(i.LEAGUE_TEXT_COLORS,s.LEAGUE_TEXT_COLORS);});
test('Public historical projection includes cosmetic settings, not secrets',()=>{const s=fixture();s.LEAGUE_TEXT_COLORS={header:'#fff2b1'};const out=lib.filterPublicState(s);assert.deepEqual(out.LEAGUE_TEXT_COLORS,s.LEAGUE_TEXT_COLORS);for(const u of Object.values(out.users))assert.equal(u.pass,undefined);});
test('League A settings do not mutate league B',async()=>{const db=createDB([{id:'liga-actual',state:fixture()},{id:'liga-b',state:fixture()}]);global.fetch=db.fetch;const before=JSON.stringify(db.state('liga-b'));const s=structuredClone(db.state());s.LEAGUE_TEXT_COLORS={light:'#123456'};assert.equal((await call(require('../api/save'),req(db,'admin',{state:s,ligaId:'liga-actual'}))).status,200);assert.equal(JSON.stringify(db.state('liga-b')),before);});
test('Finalized league still rejects cosmetic writes',async()=>{const db=createDB([{id:'liga-actual',state:fixture(),estado:'finalizada'}]);global.fetch=db.fetch;const s=structuredClone(db.state());s.LEAGUE_TEXT_COLORS={light:'#123456'};assert.equal((await call(require('../api/save'),req(db,'admin',{state:s,ligaId:'liga-actual'}))).status,403);});
test('Rule viewer remains a named native scroll region with page chaining',()=>{const src=fs.readFileSync(path.join(__dirname,'../public/reglamento.js'),'utf8'),css=fs.readFileSync(path.join(__dirname,'../public/ui-modern.css'),'utf8');assert.match(src,/class="rg-reader" tabindex="0" role="region"/);assert.match(css,/overflow:auto;overscroll-behavior:auto/);assert.match(css,/@media print\{#view-reglamento/);});
