'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {createDB,fixture,match,req,call}=require('./support/mock-db.cjs');
const route=require('../api/_rating'),handler=require('../api/liga');
function setup(){const a=fixture();a.matches=[match({status:'confirmed'})];const b=structuredClone(a);b.users.Alicia.tel='private-phone';b.users.Alicia.pass='private-password';b.users.Alicia.historialId='canonical-a';a.users.Alicia.historialId='canonical-a';return createDB([{id:'liga-actual',state:a},{id:'past',state:b,estado:'finalizada'}]);}
async function run(fn){const db=setup(),old=global.fetch;global.fetch=db.fetch;try{return await fn(db);}finally{global.fetch=old;}}
const request=(db,name='Alicia',body={})=>req(db,name,body,{operacion:'rating'});
for(const name of ['Alicia','admin','superadmin'])test('RT440 API snapshot: '+name+' can read every sporting league',()=>run(async db=>{const r=await call(handler,request(db,name));assert.equal(r.status,200);assert.equal(r.body.leagues.length,2);assert.equal(r.body.complete,true);assert.equal(r.body.window,50);assert.equal(r.body.matchCount,2);assert.equal(r.body.scope,'all-registered');}));
test('RT440 API guest: only finalized leagues; no active profile leakage',()=>run(async db=>{const r=await call(handler,{method:'POST',headers:{},query:{operacion:'rating'},body:{}});assert.equal(r.status,200);assert.deepEqual(r.body.leagues.map(x=>x.id),['past']);assert.equal(r.body.byLeague['liga-actual'],undefined);assert.equal(r.body.scope,'finalized-public');}));
test('RT440 API invalid token: does not silently become a public successful calculation',()=>run(async db=>{const r=await call(handler,{...request(db),headers:{authorization:'Bearer invalid'}});assert.equal(r.status,401);}));
test('RT440 API inactive source account: denied, even after a previous cache hit',()=>run(async db=>{const q=request(db);assert.equal((await call(handler,q)).status,200);db.state().users.Alicia.inactive=true;assert.equal((await call(handler,q)).status,401);}));
test('RT440 API revoked epoch: cannot use a cached sporting universe',()=>run(async db=>{const q=request(db);await call(handler,q);db.tables.sohail_account_security.find(x=>x.id===require('./support/mock-db.cjs').lib.principalKey('Alicia',db.state().users.Alicia)).epoch++;assert.equal((await call(handler,q)).status,401);}));
test('RT440 API default password: guard stays enabled',()=>run(async db=>{const q=request(db);db.tables.sohail_account_security.find(x=>x.id===require('./support/mock-db.cjs').lib.principalKey('Alicia',db.state().users.Alicia)).must_change=true;assert.equal((await call(handler,q)).status,403);}));
test('RT440 API private data: full snapshots never serialize contacts, passwords, logs or raw states',()=>run(async db=>{db.state().LOG=['hidden-log'];db.state().JOIN_REQUESTS=[{email:'secret'}];const r=await call(handler,request(db));const s=JSON.stringify(r.body);for(const value of ['private-phone','private-password','hidden-log','pass_hash','_credentialId','@example.invalid','JOIN_REQUESTS'])assert.ok(!s.includes(value),value);assert.equal(r.headers['Cache-Control'],'no-store');assert.equal(r.headers.Vary,'Authorization');}));
test('RT440 API read-only: no writes / session switching / operation commits',()=>run(async db=>{await call(handler,request(db));assert.ok(db.requests.every(x=>x.method==='GET'||(x.name==='sohail_p2_session'&&x.body.p_action==='read')));}));
test('RT440 API client state or rating injection: rejected',()=>run(async db=>{const r=await call(handler,request(db,'admin',{state:{},seeds:{Alicia:16}}));assert.equal(r.status,400);}));
test('RT440 API failed league read: no complete=true or partial success',()=>run(async db=>{db.fault=({name})=>name==='liga_state';const r=await call(handler,request(db));assert.equal(r.status,503);assert.equal(r.body.complete,undefined);}));
test('RT440 API missing indexed state: fail closed rather than omit that league',()=>run(async db=>{db.tables.liga_state=db.tables.liga_state.filter(x=>x.id!=='past');const r=await call(handler,request(db));assert.equal(r.status,503);assert.equal(r.body.code,'RATING_SOURCE_INCOMPLETE');}));
test('RT440 API archive-only corruption does not expose errors for an inaccessible active league to guests',()=>run(async db=>{db.state().matches=null;const r=await call(handler,{method:'POST',headers:{},query:{operacion:'rating'},body:{}});assert.equal(r.status,200);}));
test('RT440 API invalid sporting score: explicit error, not fewer matches',()=>run(async db=>{db.state('past').matches[0].sets=[[-5,6],[6,0]];const r=await call(handler,request(db));assert.equal(r.status,422);assert.equal(r.body.code,'INVALID_SCORE');}));
test('RT440 API changes during reading: retry and publish only two equal snapshots',()=>run(async db=>{let n=0;const raw=global.fetch;global.fetch=async(u,o)=>{if(String(u).includes('liga_index')&&String(u).includes('offset=0')){n++;if(n===2)db.state('past')._v++;}return raw(u,o);};const r=await call(handler,request(db));assert.equal(r.status,200);assert.equal(r.body.leagues.find(x=>x.id==='past').version,4);assert.equal(n,4);}));
test('RT440 API persistent concurrent change: explicit 409, no subset',()=>run(async db=>{const raw=global.fetch;global.fetch=async(u,o)=>{if(String(u).includes('liga_index')&&String(u).includes('offset=0'))db.state('past')._v++;return raw(u,o);};const r=await call(handler,request(db));assert.equal(r.status,409);assert.equal(r.body.code,'RATING_SOURCE_CHANGED');}));
test('RT440 API security revalidated after history read',()=>run(async db=>{const raw=global.fetch;let n=0;global.fetch=async(u,o)=>{if(String(u).includes('liga_index')&&String(u).includes('offset=0')&&++n===2)db.state().users.Alicia.inactive=true;return raw(u,o);};assert.equal((await call(handler,request(db))).status,401);}));
test('RT440 API all leagues: pagination does not cap at default 1000 or a single page',()=>run(async db=>{const s=fixture();s.users={};db.setStates(Array.from({length:260},(_,i)=>({id:'l-'+String(i).padStart(3,'0'),state:s,estado:'finalizada'})));const r=await call(handler,{method:'POST',headers:{},query:{operacion:'rating'},body:{}});assert.equal(r.status,200);assert.equal(r.body.leagues.length,260);assert.ok(db.requests.some(x=>x.query.includes('offset=250')));}));
test('RT440 API same input produces same versioned snapshot regardless of browsing another league',()=>run(async db=>{const a=await call(handler,request(db)),b=await call(handler,request(db));assert.equal(a.body.snapshot,b.body.snapshot);assert.deepEqual(a.body.info,b.body.info);}));
test('RT440 API provenance details: separate bounded response belongs to exact snapshot',()=>run(async db=>{const first=(await call(handler,request(db))).body,key=first.byLeague['liga-actual'].Alicia;const details=await call(handler,request(db,'Alicia',{snapshot:first.snapshot,playerKey:key}));assert.equal(details.status,200);assert.equal(details.body.selected.length,2);assert.equal(Object.values(first.info)[0].selected,undefined);}));
test('RT440 API stale details request: cannot mix two versions',()=>run(async db=>{const first=(await call(handler,request(db))).body;db.state('past')._v++;const details=await call(handler,request(db,'Alicia',{snapshot:first.snapshot,playerKey:first.byLeague['liga-actual'].Alicia}));assert.equal(details.status,409);}));
test('RT440 API live source strings supported without mutating original data',()=>run(async db=>{const before=JSON.stringify(db.tables);db.tables.liga_state.find(x=>x.id==='past').data=JSON.stringify(db.state('past'));const r=await call(handler,request(db));assert.equal(r.status,200);assert.equal(typeof db.tables.liga_state.find(x=>x.id==='past').data,'string');assert.ok(before.includes('private-password'));}));

// v4.5: the rejected research variant cannot be selected through the live API.
test('RT450 API active method is the protected baseline plus diagnostic confidence',()=>run(async db=>{
 const r=await call(handler,request(db));assert.equal(r.status,200);assert.equal(r.body.version,'sohail-rating-4.6.0');assert.equal(r.body.method.window,50);assert.equal(r.body.method.opponentMode,'count');assert.equal(typeof r.body.weakBridgeCount,'number');
 const p=r.body.info[r.body.byLeague['liga-actual'].Alicia];assert.ok(Array.isArray(p.confidenceReasons));assert.equal(typeof p.opponentIndependentSupport,'number');
}));
for(const who of ['admin','superadmin'])test('RT450 API '+who+' cannot activate experimental weights with a request',()=>run(async db=>{
 const r=await call(handler,request(db,who,{opponentMode:'independent',opponentFloor:0.75}));assert.equal(r.status,400);assert.ok(db.requests.every(x=>x.method==='GET'||(x.name==='sohail_p2_session'&&x.body.p_action==='read')));
}));
test('RT450 API detailed provenance includes weight factors and independent evidence without contacts',()=>run(async db=>{
 const first=(await call(handler,request(db))).body,key=first.byLeague['liga-actual'].Alicia;
 const r=await call(handler,request(db,'Alicia',{snapshot:first.snapshot,playerKey:key}));assert.equal(r.status,200);
 for(const m of r.body.selected){assert.equal(m.weight,m.timeWeight*m.opponentWeight);assert.equal(typeof m.independentOpponentMatches,'number');assert.ok(m.opponentKey);}
 assert.ok(!JSON.stringify(r.body).includes('private-phone'));
}));
