'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const {createDB,fixture,match,req,call,lib}=require('./support/mock-db.cjs');
const V=require('../api/_validation'),H=require('../public/match-history'),S=require('../public/score-rules');
async function withDB(run){const prev=global.fetch,db=createDB();global.fetch=db.fetch;try{return await run(db);}finally{global.fetch=prev;}}
const allow=a=>a.status===503;
test('SEC01: permission read failure is a 503, not permission',()=>withDB(async db=>{db.fault=()=>true;await assert.rejects(lib.blockedUserCached({u:'Alicia'},'liga-actual'),allow);}));
test('SEC02: nonexistent league is denied',()=>withDB(async()=>assert.ok(await lib.blockedUserCached({u:'Alicia'},'missing'))));
test('SEC03: no stale permission cache after deactivation',()=>withDB(async db=>{const s={u:'Alicia',pk:'g:profile-0',exp:Date.now()+60000};assert.equal(await lib.blockedUserCached(s,'liga-actual'),null);db.state().users.Alicia.inactive=true;assert.ok(await lib.blockedUserCached(s,'liga-actual'));}));
test('SEC04: rate-limit read unavailable fails closed',()=>withDB(async db=>{db.fault=({name})=>name==='rate_limits';await assert.rejects(lib.rateLimitCheck('u:test',5),allow);}));
test('SEC05: malformed rate-limit response fails closed',async()=>{const prev=global.fetch;global.fetch=async()=>({ok:true,json:async()=>({error:'bad'})});try{await assert.rejects(lib.rateLimitCheck('u:test',5),allow);}finally{global.fetch=prev;}});
test('SEC06: failed counter write is not silently ignored',()=>withDB(async db=>{db.fault=({method})=>method==='POST';await assert.rejects(lib.rateLimitFail('u:test',5,300000),allow);}));
test('SEC07: concurrent failures reach limit without lost updates',()=>withDB(async db=>{db.latency=1;const replies=await Promise.allSettled(Array.from({length:12},()=>lib.rateLimitFail('u:test',5,300000)));assert.equal(db.tables.rate_limits[0].n,5);assert.ok(await lib.rateLimitCheck('u:test',5));assert.ok(replies.every(r=>r.status==='fulfilled'||r.reason.status===503));}));
test('SEC08: expired counter resets with conditional write',()=>withDB(async db=>{db.tables.rate_limits=[{key:'u:test',n:5,until_ts:new Date(Date.now()-1000).toISOString(),updated_at:new Date(Date.now()-300000).toISOString()}];assert.equal(await lib.rateLimitCheck('u:test',5),0);await lib.rateLimitFail('u:test',5,300000);assert.equal(db.tables.rate_limits[0].n,1);}));
test('SEC09: clear uses CAS and does not erase a later failure',()=>withDB(async db=>{await lib.rateLimitFail('u:test',5,300000);const original=db.fetch;global.fetch=async(u,o)=>{if(o?.method==='DELETE'){db.tables.rate_limits[0].n=2;db.tables.rate_limits[0].updated_at=new Date(Date.now()+2).toISOString();}return original(u,o);};await lib.rateLimitClear('u:test');assert.equal(db.tables.rate_limits[0].n,2);}));
test('SEC10: hash is not the current password',()=>{const h=lib.hashV2('prueba123');assert.equal(lib.verifyPassword(h,h),false);assert.equal(lib.verifyPassword(h,'prueba123'),true);assert.equal(lib.verifyPassword(lib.hashV1('old'),'old'),true);assert.equal(lib.verifyPassword('legacy','legacy'),true);});
test('SEC11: change-password rejects stored hash without writes',()=>withDB(async db=>{const r=await call(require('../api/password'),req(db,'Alicia',{oldPass:db.state().users.Alicia.pass,newPass:'nueva1234',ligaId:'liga-actual'}));assert.equal(r.status,400);assert.equal(db.requests.some(r=>r.name==='sohail_change_password'),false);}));
test('SEC12: legitimate password change revokes old token',()=>withDB(async db=>{const token=db.token();const r=await call(require('../api/password'),req(db,'Alicia',{oldPass:'prueba123',newPass:'nueva1234',ligaId:'liga-actual'}));assert.equal(r.status,200);assert.equal(await lib.auth({headers:{authorization:'Bearer '+token}}),null);}));
for(const field of ['pass','user'])test('SEC13: oversized '+field+' rejected before DB',()=>withDB(async db=>{const r=await call(require('../api/login'),{method:'POST',headers:{},body:{user:'Alicia',pass:'prueba123',[field]:'X'.repeat(300)},query:{}});assert.equal(r.status,400);assert.equal(db.requests.length,0);}));
for(const value of ['',null,'../bad','CAPS',[],23])test('SEC14: explicit invalid league '+JSON.stringify(value),()=>assert.throws(()=>lib.resolveLigaId(value),e=>e.code==='INVALID_LEAGUE'));
test('SEC15: only omitted league retains default',()=>assert.equal(lib.resolveLigaId(),lib.LIGA_DEFAULT));
for(const endpoint of ['save','state','password','passkey'])test('SEC16: '+endpoint+' refuses invalid league',()=>withDB(async db=>{const request=req(db,'Alicia',{state:lib.filterForSession(structuredClone(db.state()),{u:'Alicia'}),oldPass:'prueba123',newPass:'nueva1234',ligaId:'../bad',accion:'list'},{liga:'../bad'},endpoint==='state'?'GET':'POST');const r=await call(require('../api/'+endpoint),request);assert.equal(r.status,400);assert.equal(db.requests.some(x=>x.name==='sohail_write_state'||x.name==='sohail_change_password'),false);}));
test('SEC17: forged role cannot read admin data',()=>withDB(async db=>{const token=lib.signToken({u:'Alicia',r:'superadmin',src:'liga-actual',pk:'g:profile-0',sv:0,exp:Date.now()+60000});const r=await call(require('../api/state'),{method:'GET',headers:{authorization:'Bearer '+token},query:{liga:'liga-actual'}});assert.equal(r.status,200);assert.equal(r.body.role,'player');assert.ok(!r.body.state.users.Beto.email);assert.ok(!r.body.state.users.admin.pass);}));
test('SEC18: session from another identity is denied',()=>withDB(async db=>{const r=await call(require('../api/state'),{method:'GET',headers:{authorization:'Bearer '+lib.signToken({u:'Beto',r:'admin',src:'liga-actual',pk:'g:profile-0',sv:0,exp:Date.now()+60000})},query:{liga:'liga-actual'}});assert.equal(r.status,401);}));
test('DATA01: pending result cannot be moved to another group',()=>{const s=fixture();s.cycles[0].groups.push(structuredClone(s.cycles[0].groups[0]));s.matches=[match()];const i=structuredClone(s);i.matches[0].g=2;assert.throws(()=>V.protectState(s,i,{u:'Alicia'},false,false),e=>e.status===403);});
test('DATA02: W.O. requires club on server',()=>{const s=fixture();assert.throws(()=>V.validateMatch(match({wo:true,sets:[],retiroDe:'Beto',winner:'Alicia',club:''}),s,true),e=>e.status===400);});
test('DATA03: No jugado keeps its existing exception',()=>V.validateMatch(match({np:true,sets:[],date:'',club:'',status:'confirmed'}),fixture(),true));
test('DATA04: server derives playoff label',()=>{const s=fixture();s.playoff={started:true,tramos:[{label:'A',main:[[{a:'Alicia',b:'Beto'}]]}]};const i=structuredClone(s);i.matches=[match({po:true,poNames:['Alicia','Beto'],ti:0,which:'main',ri:0,mi:0,tLabel:'<img src=x>',winner:'Alicia'})];V.protectState(s,i,{u:'Alicia'},false,false);assert.equal(i.matches[0].tLabel,'A');});
for(const broken of [null,[-1,6],['6',2],[6,2,9],{},[2.5,6]])test('STAT01: corrupt set '+JSON.stringify(broken)+' never discarded to invent winner',()=>assert.equal(H.winner(match({status:'confirmed',sets:[[6,3],broken,[6,2]]})),null));
test('STAT02: three PO participants do not become two',()=>assert.equal(H.records([match({po:true,poNames:['Alicia','Beto','Ciro']})],'Alicia').length,0));
test('STAT03: self-play excluded',()=>assert.equal(H.records([match({bName:'Alicia'})],'Alicia').length,0));
test('STAT04: contradictory retirement unresolved',()=>assert.equal(H.winner(match({wo:true,sets:[[6,2]],retiroDe:'Alicia',winner:'Alicia'})),null));
test('STAT05: already finished RET cannot invent a win',()=>assert.equal(H.winner(match({wo:true,sets:[[6,2],[6,2]],retiroDe:'Alicia',winner:'Beto'})),null));
test('STAT06: malformed match included as unresolved, not a win',()=>{const s=H.summarize([match({status:'confirmed',sets:[[6,3],null,[6,2]]})],'Alicia');assert.equal(s.played,0);assert.equal(s.unresolved,1);});
test('STAT07: date not ID decides recent order',()=>assert.deepEqual([match({id:99,date:'2020-01-01'}),match({id:1,date:'2026-01-01'})].sort(H.newest).map(m=>m.id),[1,99]));
test('RULE01: legal sets and match formats match independent oracle (32805 candidates)',()=>{let n=0;function v(a,b){return Number.isInteger(a)&&Number.isInteger(b)&&a>=0&&b>=0&&((a===6&&b<=4)||(b===6&&a<=4)||(a===7&&(b===5||b===6))||(b===7&&(a===5||a===6)));}for(let a=0;a<=8;a++)for(let b=0;b<=8;b++)for(let c=0;c<=8;c++)for(let d=0;d<=8;d++)for(const tb of [null,[1,0],[0,1],[0,0],[10,8]]){const split=(a>b)!==(c>d);const expected=v(a,b)&&v(c,d)&&(split?!!tb&&((tb[0]===1&&tb[1]===0)||(tb[0]===0&&tb[1]===1)):tb===null);assert.equal(S.validMatch([[a,b],[c,d],...(tb?[tb]:[])]).ok,expected);n++;}assert.equal(n,32805);});
// Passkey option tests exercise real route logic; the cryptographic verifier is
// a spy here, NOT a physical authenticator test or a library crypto audit.
function passkeyWithSpy(spy){const code=fs.readFileSync(path.join(__dirname,'../api/passkey.js'),'utf8').replace("await import('@simplewebauthn/server')","await __wa()");const mod={exports:{}};const ctx={module:mod,exports:mod.exports,require:p=>p==='./_lib'||p==='./_lib.js'?lib:p.startsWith('./')?require(path.join(__dirname,'../api',p)):require(p),__wa:async()=>spy,Buffer,process,console,fetch:(...a)=>global.fetch(...a),Date,JSON};vm.createContext(ctx);vm.runInContext(code,ctx);return mod.exports;}
test('KEY01: registration requests user verification and binds challenge',()=>withDB(async db=>{let opts;const h=passkeyWithSpy({generateRegistrationOptions:async o=>(opts=o,{challenge:'fake-test-challenge'})});const r=await call(h,req(db,'Alicia',{accion:'reg-start',ligaId:'liga-actual'}));assert.equal(r.status,200);assert.equal(opts.authenticatorSelection.userVerification,'required');const cookie=r.headers['Set-Cookie'].split(';')[0].split('=')[1];const payload=JSON.parse(Buffer.from(cookie.split('.')[0],'base64url'));assert.equal(payload.pk,'g:profile-0');assert.equal(payload.sv,0);}));
test('KEY02: registration finish from an obsolete epoch is rejected before verifier',()=>withDB(async db=>{let verified=false;const h=passkeyWithSpy({generateRegistrationOptions:async()=>({challenge:'fake-test-challenge'}),verifyRegistrationResponse:async()=>{verified=true;return {verified:true};}});const first=await call(h,req(db,'Alicia',{accion:'reg-start'}));db.tables.sohail_account_security.find(x=>x.id==='g:profile-0').epoch++;const request=req(db,'Alicia',{accion:'reg-finish',cred:{}});request.headers.cookie=first.headers['Set-Cookie'].split(';')[0];const r=await call(h,request);assert.equal(r.status,400);assert.equal(verified,false);}));
test('KEY03: registration response verification requires UV',()=>withDB(async db=>{let opts;const h=passkeyWithSpy({generateRegistrationOptions:async()=>({challenge:'fake'}),verifyRegistrationResponse:async o=>(opts=o,{verified:false})});const first=await call(h,req(db,'Alicia',{accion:'reg-start'}));const request=req(db,'Alicia',{accion:'reg-finish',cred:{id:'test'}});request.headers.cookie=first.headers['Set-Cookie'].split(';')[0];const r=await call(h,request);assert.equal(r.status,400);assert.equal(opts.requireUserVerification,true);assert.equal(db.tables.passkeys.length,0);}));
test('KEY04: authentication response verification requires UV',()=>withDB(async db=>{let opts;db.tables.passkeys=[{credential_id:'test',user_name:'Alicia',public_key:'AA',counter:0}];const h=passkeyWithSpy({generateAuthenticationOptions:async o=>{assert.equal(o.userVerification,'required');return{challenge:'fake'};},verifyAuthenticationResponse:async o=>(opts=o,{verified:false})});const first=await call(h,req(db,'Alicia',{accion:'auth-start'}));const request=req(db,'Alicia',{accion:'auth-finish',cred:{id:'test'}});request.headers.cookie=first.headers['Set-Cookie'].split(';')[0];const r=await call(h,request);assert.equal(r.status,401);assert.equal(opts.requireUserVerification,true);}));

test('DATA05: temporary statistics identity hints are not stored',()=>{const s=fixture(),i=structuredClone(s);i.matches=[match({_mhSubject:'Ciro',_mhPlayerIds:['profile-2','profile-1'],_mhLeagueId:'other'})];V.protectState(s,i,{u:'Alicia'},false,false);assert.ok(!Object.keys(i.matches[0]).some(k=>k.startsWith('_mh')));assert.equal(i.matches[0].aName,'Alicia');});

test('H2H01: swapping players swaps wins/losses; W.O. explicit and pending excluded',()=>{const context={id:'liga-actual',users:fixture().users},list=[match({status:'confirmed'}),match({id:2,status:'confirmed',wo:true,sets:[],retiroDe:'Alicia',winner:'Beto'}),match({id:3,status:'pending',sets:[[6,0],[6,0]]})];const a=H.headToHead(list,'Alicia',H.person('Beto',context).key,context),b=H.headToHead(list,'Beto',H.person('Alicia',context).key,context);assert.equal(a.wins,b.losses);assert.equal(a.losses,b.wins);assert.equal(a.decided,2);assert.equal(a.wo,1);assert.equal(a.pending,1);});
test('H2H02: global profile links, not equal names, distinguish opponents',()=>{const a=H.person('Beto',{id:'one',users:{Beto:{jugadorId:'one'}}}),b=H.person('Beto',{id:'two',users:{Beto:{jugadorId:'two'}}}),c=H.person('Alias Beto',{id:'three',users:{'Alias Beto':{jugadorId:'one'}}});assert.notEqual(a.key,b.key);assert.equal(a.key,c.key);});
