'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto'),fs=require('node:fs'),path=require('node:path');
const R=require('../api/_request-security'),H=require('../api/_http'),C=require('../api/_content-security'),B=require('../api/_backup-security'),I=require('../public/import-security'),M=require('./support/mock-db.cjs');
const request=(body={},more={})=>({method:'POST',headers:{host:'sohail.test',origin:'https://sohail.test','content-type':'application/json','sec-fetch-site':'same-origin'},query:{},body,...more});
async function run(fn,storage=false){const db=storage?require('./support/backup-db.cjs').create():M.createDB(),old=global.fetch,env={...process.env};global.fetch=db.fetch;try{return await fn(db);}finally{global.fetch=old;process.env=env;}}
const bad=(fn,code)=>assert.throws(fn,e=>e.code===code);
for(const route of Object.keys(R.METHODS))test('P3 methods: '+route+' rejects unreviewed method before DB',()=>{bad(()=>R.validate(request({}, {method:'TRACE'}),route),'METHOD_NOT_ALLOWED');});
for(const site of ['cross-site','same-site'])test('P3 browser origin rejects '+site,()=>{const q=request();q.headers['sec-fetch-site']=site;bad(()=>R.validate(q,'liga'),'REQUEST_ORIGIN');});
for(const origin of ['https://evil.test','http://sohail.test','null','https://sohail.test/','https://u:pw@sohail.test'])test('P3 origin rejects '+origin,()=>{const q=request();q.headers.origin=origin;bad(()=>R.validate(q,'liga'),'REQUEST_ORIGIN');});
test('P3 same origin is accepted; origin controls do not grant an identity',()=>run(async db=>{const r=await M.call(require('../api/state'),request({}, {method:'GET',query:{liga:'liga-actual'}}));assert.equal(r.status,401);assert.equal(r.body.state,undefined);}));
test('P3 duplicate query parameter rejected without DB',()=>run(async db=>{const r=await M.call(require('../api/state'),request({}, {method:'GET',query:{liga:['a','b']}}));assert.equal(r.status,400);assert.equal(db.requests.length,0);}));
for(const body of ['{}',[],null])test('P3 rejects non-object body '+JSON.stringify(body),()=>{bad(()=>R.validate(request(body),'liga'),'INVALID_REQUEST');});
test('P3 form payload rejected as unsupported media type',()=>{const q=request();q.headers['content-type']='text/plain';bad(()=>R.validate(q,'liga'),'JSON_REQUIRED');});
for(const k of ['__proto__','constructor','prototype'])test('P3 unsafe object key '+k,()=>{bad(()=>R.validateTree(JSON.parse('{"a":{"'+k+'":{}}}')),'UNSAFE_OBJECT_KEY');});
test('P3 depth, cycles and non-finite numbers rejected; repeated object references are allowed',()=>{const a={};a.self=a;bad(()=>R.validateTree(a),'INVALID_REQUEST');let x={};for(let i=0;i<60;i++)x={x};bad(()=>R.validateTree(x),'REQUEST_COMPLEXITY');bad(()=>R.validateTree({x:NaN}),'INVALID_REQUEST');const shared={x:1};R.validateTree([shared,shared]);});
test('P3 content length and actual byte count both enforce upper bound',()=>{const q=request();q.headers['content-length']='9999999';bad(()=>R.validate(q,'save'),'REQUEST_TOO_LARGE');bad(()=>R.validate(request({x:'x'.repeat(270000)}),'password'),'REQUEST_TOO_LARGE');});
test('P3 preview APIs disabled unless an explicit isolated preview is configured',()=>{const old=process.env.VERCEL_ENV,allow=process.env.SOHAIL_PREVIEW_DATA_ACCESS;try{process.env.VERCEL_ENV='preview';delete process.env.SOHAIL_PREVIEW_DATA_ACCESS;bad(()=>R.validate(request(),'liga'),'PREVIEW_DATA_DISABLED');process.env.SOHAIL_PREVIEW_DATA_ACCESS='1';R.validate(request(),'liga');}finally{if(old===undefined)delete process.env.VERCEL_ENV;else process.env.VERCEL_ENV=old;if(allow===undefined)delete process.env.SOHAIL_PREVIEW_DATA_ACCESS;else process.env.SOHAIL_PREVIEW_DATA_ACCESS=allow;}});
test('P3 quota address cannot be forged on a non-Vercel host',()=>{const old=process.env.VERCEL;try{delete process.env.VERCEL;assert.equal(R.address({headers:{'x-forwarded-for':'8.8.8.8'},socket:{remoteAddress:'192.0.2.3'}}),'192.0.2.3');process.env.VERCEL='1';assert.equal(R.address({headers:{'x-vercel-forwarded-for':'::ffff:192.0.2.8','x-forwarded-for':'8.8.8.8'}}),'192.0.2.8');assert.equal(R.address({headers:{'x-forwarded-for':'not-an-ip'}}),'unknown');}finally{if(old===undefined)delete process.env.VERCEL;else process.env.VERCEL=old;}});
for(const kind of Object.keys(R.LIMITS))test('P3 shared '+kind+' budget rejects cap+1',()=>run(async db=>{for(let i=0;i<R.LIMITS[kind];i++)await R.consume(request(),kind,'same-client');await assert.rejects(R.consume(request(),kind,'same-client'),e=>e.code==='REQUEST_RATE_LIMIT'&&e.retryAfter>=1);assert.ok(/^[a-f0-9]{64}$/.test(db.tables.sohail_request_budgets[0].key_hash));assert.ok(!JSON.stringify(db.tables.sohail_request_budgets).includes('same-client'));}));
test('P3 quota outage fails closed and never calls business handler',()=>run(async db=>{db.fault=q=>q.name==='sohail_p3_budget';let called=false;const r=await M.call(H.wrap(()=>{called=true;},{route:'state'}),request({}, {method:'GET'}));assert.equal(r.status,503);assert.equal(called,false);}));
test('P3 errors are no-store, localized and contain a reference, not secret details',async()=>{const r=await M.call(H.wrap((q,s)=>s.status(500).json({error:'RAW_PASSWORD',body:'RAW_TOKEN',stack:'RAW_SQL'})),request({}, {headers:{'accept-language':'en'}}));assert.equal(r.headers['Cache-Control'],'no-store');assert.equal(r.headers['X-Content-Type-Options'],'nosniff');assert.match(r.body.requestId,/^[a-f0-9-]{36}$/);assert.match(r.body.error,/could not/);assert.ok(!JSON.stringify(r.body).includes('RAW_'));});
test('P3 response Retry-After explains a throttled request without mutation',()=>run(async db=>{const h=H.wrap((q,s)=>s.status(200).json({ok:true}),{route:'health'});for(let i=0;i<120;i++)assert.equal((await M.call(h,request({}, {method:'GET'}))).status,200);const r=await M.call(h,request({}, {method:'GET'}));assert.equal(r.status,429);assert.ok(+r.headers['Retry-After']>=1);}));
const png='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jY9sAAAAASUVORK5CYII=';
test('P3 picture accepts bounded raster signature',()=>assert.equal(C.safeImage(png),png));
for(const src of ['data:image/svg+xml;base64,PHN2Zz4=','data:text/html;base64,WA==','https://evil.test/a.png','data:image/png;base64,QUFBQQ==','data:image/png;base64,@@@'])test('P3 picture rejects '+src.slice(0,35),()=>assert.equal(C.safeImage(src),''));
test('P3 image dimensions cannot be a billion pixels',()=>{const a=Buffer.alloc(24);Buffer.from(png.split(',')[1],'base64').copy(a);a.writeUInt32BE(1000000,16);assert.equal(C.safeImage('data:image/png;base64,'+a.toString('base64')),'');});
test('P3 legacy unsafe message image removed in read projection, not from stored history',()=>{const m={texto:'Hola',imagen:'data:image/svg+xml;base64,PHN2Zz4='};assert.equal(C.message(m).imagen,null);assert.ok(m.imagen);});
test('P3 login header contains only reviewed colors and HTTP links',()=>{const out=C.headerConfig({color:'red; background:url(https://bad)',links:[{text:'OK',url:'https://example.org/x'},{text:'Bad',url:'javascript:alert(1)'},{text:'Bad',url:'https://u:p@example.org'},{text:'Bad',url:'https://example.org/" onmouseover=x'}]});assert.equal(out.color,'#0E3470');assert.equal(out.links.length,1);assert.equal(out.links[0].text,'OK');});
function sample(){const tables=Object.fromEntries(B.TABLES.map(t=>[t,[]]));tables.liga_state=[{id:'league',data:{matches:[{id:1,score:'6-3'}],users:{A:{pass:'PRIVATE-TEST-HASH'}}}}];return {version:3,consistency:'single-statement-snapshot',generated_at:new Date().toISOString(),tables,counts:Object.fromEntries(B.TABLES.map(t=>[t,tables[t].length]))};}
const secret=()=>crypto.randomBytes(32).toString('hex');
test('P3 encrypted backup round-trip preserves all persistent values and counts',async()=>{const s=sample(),k=secret(),bytes=await B.seal(s,k);assert.ok(!bytes.includes(Buffer.from('PRIVATE-TEST-HASH')));assert.deepEqual((await B.open(bytes,k)).snapshot,s);});
test('P3 encryption produces a new nonce for the same content',async()=>{const s=sample(),k=secret();assert.notDeepEqual(await B.seal(s,k),await B.seal(s,k));});
test('P3 wrong key and payload corruption are rejected',async()=>{const k=secret(),b=await B.seal(sample(),k);await assert.rejects(B.open(b,secret()));b[b.length-1]^=1;await assert.rejects(B.open(b,k));});
test('P3 encryption authenticates metadata as well as data',async()=>{const k=secret(),b=await B.seal(sample(),k,'primary'),at=b.indexOf(Buffer.from('primary'));b[at]=112+1;await assert.rejects(B.open(b,k));});
test('P3 partial/truncated/wrong format backup cannot verify',async()=>{const k=secret(),b=await B.seal(sample(),k);for(const cut of [0,10,30,b.length-3])await assert.rejects(B.open(b.subarray(0,cut),k));await assert.rejects(B.open(Buffer.from('{}'),k));});
test('P3 snapshot must contain exactly persistent tables; sessions cannot sneak in',async()=>{const s=sample();s.tables.sohail_auth_sessions=[];await assert.rejects(B.seal(s,secret()));});
test('P3 snapshot count mismatch cannot be uploaded',async()=>{const s=sample();s.counts.liga_state=0;await assert.rejects(B.seal(s,secret()));});
test('P3 missing encryption key never falls back to gzip/plaintext',()=>run(async db=>{process.env.BACKUP_SECRET='synthetic-backup';delete process.env.BACKUP_ENCRYPTION_KEY;const r=await M.call(require('../api/backup'),{method:'GET',headers:{'x-backup-secret':'synthetic-backup'}});assert.equal(r.status,503);assert.equal(r.body.code,'BACKUP_KEY_REQUIRED');assert.equal(db.storageCalls.length,0);},true));
test('P3 unauthenticated backup request performs no private reads',()=>run(async db=>{const r=await M.call(require('../api/backup'),{method:'GET',headers:{}});assert.equal(r.status,401);assert.equal(db.requests.length,0);assert.equal(db.storageCalls.length,0);},true));
test('P3 public bucket refuses backup upload',()=>run(async db=>{process.env.BACKUP_SECRET='synthetic-backup';process.env.BACKUP_ENCRYPTION_KEY=secret();db.bucketPublic=true;const r=await M.call(require('../api/backup'),{method:'GET',headers:{'x-backup-secret':'synthetic-backup'}});assert.equal(r.status,503);assert.equal(r.body.code,'BACKUP_BUCKET_NOT_PRIVATE');assert.equal(db.backupObjects.size,0);},true));
test('P3 corrupted read-back is not reported as verified and never deletes backups',()=>run(async db=>{process.env.BACKUP_SECRET='synthetic-backup';process.env.BACKUP_ENCRYPTION_KEY=secret();db.tamperDownload=true;const r=await M.call(require('../api/backup'),{method:'GET',headers:{'x-backup-secret':'synthetic-backup'}});assert.equal(r.status,503);assert.equal(r.body.code,'BACKUP_VERIFY_FAILED');assert.ok(!db.storageCalls.some(x=>x.method==='DELETE'));},true));
test('P3 secret compare does not accept empty, non-string or partial secrets',()=>{assert.equal(B.sameSecret('abc','abc'),true);for(const [a,b]of [['',''],['ab','abc'],[null,'abc'],['x',null]])assert.equal(B.sameSecret(a,b),false);});
// Minimal stored ZIP fixtures exercise the parser, not the external SheetJS code.
function zip(entries){const locals=[],central=[];let off=0;for(const [name,value]of entries){const n=Buffer.from(name),b=Buffer.from(value),h=Buffer.alloc(30),c=Buffer.alloc(46);h.writeUInt32LE(0x04034b50);h.writeUInt16LE(20,4);h.writeUInt32LE(b.length,18);h.writeUInt32LE(b.length,22);h.writeUInt16LE(n.length,26);c.writeUInt32LE(0x02014b50);c.writeUInt16LE(20,4);c.writeUInt16LE(20,6);c.writeUInt32LE(b.length,20);c.writeUInt32LE(b.length,24);c.writeUInt16LE(n.length,28);c.writeUInt32LE(off,42);locals.push(h,n,b);central.push(c,n);off+=h.length+n.length+b.length;}const cd=Buffer.concat(central),e=Buffer.alloc(22);e.writeUInt32LE(0x06054b50);e.writeUInt16LE(entries.length,8);e.writeUInt16LE(entries.length,10);e.writeUInt32LE(cd.length,12);e.writeUInt32LE(off,16);return Buffer.concat([...locals,cd,e]);}
const entries=[['[Content_Types].xml','x'],['xl/workbook.xml','x'],['xl/worksheets/sheet1.xml','x']];
test('P3 ZIP preflight accepts small structurally valid XLSX',()=>assert.equal(I.zip(zip(entries)).entries,3));
for(const name of ['../bad','/absolute','xl/../../bad','xl/vbaProject.bin','xl/externalLinks/a.xml'])test('P3 ZIP rejects '+name,()=>assert.throws(()=>I.zip(zip([...entries,[name,'x']]))));
test('P3 ZIP rejects duplicate names, encrypted entries and a bomb-sized entry',()=>{assert.throws(()=>I.zip(zip([...entries,entries[0]])));const b=zip(entries),at=b.indexOf(Buffer.from([80,75,1,2]));b.writeUInt16LE(1,at+8);assert.throws(()=>I.zip(b));const c=zip(entries);c.writeUInt32LE(100000000,at+24);assert.throws(()=>I.zip(c));});
test('P3 file limits reject empty, oversize, wrong extension and fake XLS without parsing',async()=>{for(const f of [{name:'x.xlsx',size:0},{name:'x.xlsx',size:6*1024*1024},{name:'x.exe',size:10},{name:'x.xls',size:4,arrayBuffer:async()=>new ArrayBuffer(4)}])await assert.rejects(I.file(f));assert.deepEqual(await I.file({name:'x.json',size:10},true),{format:'json'});});
test('P3 worksheet bounds reject huge ranges and macros',()=>{for(const wb of [{SheetNames:['x'],Sheets:{x:{'!ref':'A1:XFD1048576'}}},{SheetNames:['x'],Sheets:{x:{'!ref':'A1'}},vbaraw:'code'}])assert.throws(()=>I.workbook(wb));assert.ok(I.workbook({SheetNames:['x'],Sheets:{x:{'!ref':'A1:B3'}}}));});
test('P3 Excel guard refuses an old unreviewed library version',()=>assert.throws(()=>I.protect({version:'0.18.5',read(){}})));
test('P3 strict script elements, no eval, same-origin connects, no embedded frames',()=>{const v=require('../vercel.json'),c=v.headers[0].headers.find(x=>x.key==='Content-Security-Policy').value;assert.match(c,/script-src-elem 'self' https:\/\/cdn\.sheetjs\.com\/xlsx-0\.20\.3\/package\/dist\/xlsx.full.min.js;/);assert.ok(!c.includes('unsafe-eval'));assert.match(c,/connect-src 'self';/);assert.match(c,/frame-src 'none'/);assert.match(c,/script-src-attr 'unsafe-inline'/);const html=fs.readFileSync(path.join(__dirname,'../public/index.html'),'utf8');assert.ok(!/<script>/.test(html));assert.ok(html.includes('login-title.js'));});
test('P3 protected branch checker cannot mistake missing or bypassable settings for success',()=>{const F=require('../scripts/check-branch-protection.cjs').findings;assert.ok(F({}).length);assert.deepEqual(F({required_pull_request_reviews:{},required_status_checks:{strict:true,contexts:['Integridad, regresión y seguridad local']},enforce_admins:{enabled:true},allow_force_pushes:{enabled:false},allow_deletions:{enabled:false}}),[]);});
test('P3 migration has no sports UPDATE/DELETE and closes column/sequence/function permissions',()=>{const sql=fs.readFileSync(path.join(__dirname,'../10_security_part3.sql'),'utf8');assert.ok(!/DELETE FROM public\.(liga_state|jugadores|matches)|UPDATE public\.(liga_state|jugadores)|TRUNCATE|DROP TABLE/i.test(sql));for(const x of ['REVOKE SELECT','ON SEQUENCE','STABLE SECURITY INVOKER','ALTER DEFAULT PRIVILEGES','ON CONFLICT(category,key_hash)'])assert.ok(sql.includes(x),x);});
test('P3 former requirements remain: six characters and tenis exception, unchanged sporting rating',()=>{const p=require('../api/_password-security');assert.equal(p.policy('cancha7'),true);assert.equal(p.policy('abcde'),false);assert.equal(p.policy('tenis',{temporary:true}),true);assert.ok(fs.readFileSync(path.join(__dirname,'../api/_rating-engine.js'),'utf8').includes('50'));});

test('P3 audit details redact reset secrets and provider response bodies',()=>{const d=C.auditDetails({count:2,has_apikey:true,api_key:'secret',nested:{newPass:'secret',body:'provider raw url with secret'},message:'safe label'});assert.equal(d.count,2);assert.equal(d.has_apikey,true);assert.equal(d.api_key,'[redacted]');assert.equal(d.nested.newPass,'[redacted]');assert.equal(d.nested.body,'[redacted]');});

// PostgreSQL combines per-schema defaults with global defaults.
test('P3 future function defaults revoke the global PUBLIC execute grant',()=>{
 const sql=require('node:fs').readFileSync(require('node:path').join(__dirname,'../10_security_part3.sql'),'utf8');
 assert.match(sql,/ALTER DEFAULT PRIVILEGES REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC,anon,authenticated;/);
});

test('P3 actual query-routed rating and restore consume the heavy budget',()=>{
 for(const op of ['rating','restore'])assert.equal(R.category({body:{},query:{operacion:op},headers:{}},'liga'),'heavy');
 assert.equal(R.category({body:{accion:'crear'},headers:{}},'liga'),'write');
 assert.equal(R.category({body:{},query:{operacion:'injuries'},headers:{}},'liga'),'write');
 assert.equal(R.category({body:{mode:'status'},query:{operacion:'restore'},headers:{}},'liga'),'read');
});
function deflatedZip(text,declared){
 const items=[['[Content_Types].xml','x'],['xl/workbook.xml','x'],['xl/worksheets/sheet1.xml',text]],locals=[],central=[];let off=0;
 for(const [name,value]of items){const n=Buffer.from(name),raw=Buffer.from(value),b=require('node:zlib').deflateRawSync(raw),h=Buffer.alloc(30),c=Buffer.alloc(46),len=name.includes('sheet1')?(declared??raw.length):raw.length;
 h.writeUInt32LE(0x04034b50);h.writeUInt16LE(20,4);h.writeUInt16LE(8,8);h.writeUInt32LE(b.length,18);h.writeUInt32LE(len,22);h.writeUInt16LE(n.length,26);
 c.writeUInt32LE(0x02014b50);c.writeUInt16LE(20,4);c.writeUInt16LE(20,6);c.writeUInt16LE(8,10);c.writeUInt32LE(b.length,20);c.writeUInt32LE(len,24);c.writeUInt16LE(n.length,28);c.writeUInt32LE(off,42);locals.push(h,n,b);central.push(c,n);off+=h.length+n.length+b.length;}
 const cd=Buffer.concat(central),e=Buffer.alloc(22);e.writeUInt32LE(0x06054b50);e.writeUInt16LE(items.length,8);e.writeUInt16LE(items.length,10);e.writeUInt32LE(cd.length,12);e.writeUInt32LE(off,16);return Buffer.concat([...locals,cd,e]);
}
test('P3 streams the actual expanded XLSX contents before parsing',async()=>assert.equal((await I.verifyExpanded(deflatedZip('small'))).expandedBytes,7));
test('P3 lying ZIP size cannot bypass the actual expanded-content budget',async()=>{const bytes=deflatedZip('a'.repeat(200000),1);assert.ok(I.zip(bytes));await assert.rejects(I.verifyExpanded(bytes));});
test('P3 truncated deflate stream is rejected before spreadsheet parsing',async()=>{const bytes=deflatedZip('example');bytes[bytes.indexOf(Buffer.from('[Content_Types].xml'))+19]=255;await assert.rejects(I.verifyExpanded(bytes));});
test('P3 genuine stored ZIP preflight still accepts the file',async()=>assert.equal((await I.verifyExpanded(zip(entries))).expandedBytes,3));
