'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const M=require('./support/mock-db.cjs'),L=M.lib,P=require('../api/_password-security'),A=require('../api/_auth-security'),S=require('../api/_session');
const login=require('../api/login'),password=require('../api/password'),state=require('../api/state'),save=require('../api/save');
const GOOD='una frase de tenis 2026',SECOND='otra frase personal 2026';
const cookie=r=>[].concat(r.headers['Set-Cookie']||[]).map(x=>x.split(';')[0]).join('; ');
const request=(body,token='',extra={})=>({method:'POST',headers:{host:'sohail.test',origin:'https://sohail.test','content-type':'application/json','x-sohail-session':'1',...(token?{authorization:'Bearer '+token}:{}),...extra},body,query:{}});
async function run(fn,states){const db=M.createDB(states),prev=global.fetch;global.fetch=db.fetch;try{return await fn(db);}finally{global.fetch=prev;}}
const withClock=async(ms,fn)=>{const now=Date.now;try{Date.now=()=>now()+ms;return await fn();}finally{Date.now=now;}};
function asTemporary(db,name='Alicia',pass='tenis'){
 const u=db.state().users[name];u.pass=L.hashV2(pass);u.passwordTemporary=true;
 const a=db.tables.sohail_account_security.find(x=>x.id===L.principalKey(name,u));a.pass_hash=u.pass;a.must_change=true;return a;
}
function spyPasskey(spy){const source=fs.readFileSync(path.join(__dirname,'../api/passkey.js'),'utf8').replace("await import('@simplewebauthn/server')","await __wa()");const mod={exports:{}},req=require('node:module').createRequire(path.join(__dirname,'../api/passkey.js'));const context={module:mod,exports:mod.exports,require:req,Buffer,URL,process,console,Date,JSON,fetch:(...a)=>global.fetch(...a),__wa:async()=>spy};vm.createContext(context);vm.runInContext(source,context);return mod.exports;}

test('P2 PASSWORD unique salts for the same text, native scrypt verification',async()=>{const a=await P.hashPassword(GOOD),b=await P.hashPassword(GOOD);assert.notEqual(a,b);assert.ok(P.isModern(a));assert.equal(await P.verifyPassword(a,GOOD),true);assert.equal(await P.verifyPassword(a,SECOND),false);assert.equal(await P.verifyPassword(a,a),false);assert.equal(L.verifyPassword(a,a),false);});
for(const value of [null,123,{},[],undefined,'','x'.repeat(129)])test('P2 PASSWORD rejects malformed or oversized input '+String(value).slice(0,24),async()=>{assert.equal(P.validInput(value),false);assert.equal(P.policy(value),false);assert.equal(await P.verifyPassword('v1:abc',value),false);});
for(const bad of ['tenis','admin123','123456789012345','a'.repeat(20),'corta','1'.repeat(14)])test('P2 PASSWORD personal policy denies default/common/short '+bad,()=>assert.equal(P.policy(bad),false));
test('P2 PASSWORD initial/reset tenis is allowed only as temporary',()=>{assert.equal(P.policy('tenis',{temporary:true}),true);assert.equal(P.policy(GOOD,{temporary:true}),true);assert.equal(P.policy('corta',{temporary:true}),false);assert.equal(P.policy('tenis'),false);});
for(const stored of ['v1:'+crypto.createHash('sha256').update('legado123').digest('hex'),L.hashV2('legado123'),'legado123'])test('P2 PASSWORD legacy proof accepted for rehash, not hash replay '+stored.slice(0,8),async()=>{assert.equal(await P.verifyPassword(stored,'legado123'),true);assert.equal(await P.verifyPassword(stored,'incorrecta'),false);if(stored!=='legado123')assert.equal(await P.verifyPassword(stored,stored),false);});
for(const stored of ['v3:scrypt:99999999:8:3:bad','v9:x','v2:broken'])test('P2 PASSWORD unknown version/cost does not execute caller-supplied work '+stored,async()=>assert.equal(await P.verifyPassword(stored,'example'),false));
test('P2 PASSWORD preserves spaces and unicode exactly',async()=>{const text='  contraseña con espacios  ';const h=await P.hashPassword(text);assert.equal(await P.verifyPassword(h,text),true);assert.equal(await P.verifyPassword(h,text.trim()),false);});

test('P2 LOGIN tenis still works; short restricted session; no private data before change',()=>run(async db=>{
 asTemporary(db);db.state().users.Alicia.isAdmin=true;
 const r=await M.call(login,request({user:'Alicia',pass:'tenis'}));assert.equal(r.status,200);assert.equal(r.body.mustChangePw,true);
 const t=L.verifyToken(r.body.token);assert.equal(t.exp-t.iat,15*60000);assert.equal(t.m,true);assert.equal(r.body.state.users.Beto.email,undefined);assert.equal(r.body.state.LOG,undefined);
 await assert.rejects(L.auth(request({},r.body.token)),e=>e.code==='PASSWORD_CHANGE_REQUIRED');
 assert.equal(await P.verifyPassword(db.tables.sohail_account_security.find(a=>a.id===t.pk).pass_hash,'tenis'),true);
 const changed=await M.call(password,request({newPass:GOOD},r.body.token));assert.equal(changed.status,200);assert.equal(changed.body.passwordTemporary,false);
 const normal=L.verifyToken(changed.body.token);assert.equal(normal.exp-normal.iat,24*3600000);assert.equal(normal.m,false);assert.equal(await L.auth(request({},r.body.token)),null);
}));
test('P2 LOGIN legacy account migrates without forced reset or changing sporting data/version',()=>run(async db=>{
 const before=structuredClone(db.state());const r=await M.call(login,request({user:'Alicia',pass:'prueba123'}));assert.equal(r.status,200);assert.equal(r.body.mustChangePw,false);
 assert.equal(db.state()._v,before._v);assert.deepEqual(db.state().matches,before.matches);assert.deepEqual(db.state().cycles,before.cycles);
 const a=db.tables.sohail_account_security.find(x=>x.id==='g:profile-0');assert.ok(P.isModern(a.pass_hash));assert.equal(a.epoch,0);assert.equal(db.tables.jugadores.find(x=>x.id==='profile-0').pass,a.pass_hash);assert.equal(db.state().users.Alicia.pass,a.pass_hash);
}));
test('P2 LOGIN failure to migrate does not issue a session or cookie',()=>run(async db=>{db.fault=q=>q.name==='sohail_p2_rehash';const r=await M.call(login,request({user:'Alicia',pass:'prueba123'}));assert.equal(r.status,503);assert.equal(r.body.token,undefined);assert.equal(r.headers['Set-Cookie'],undefined);}));
test('P2 LOGIN failure to persist session fails closed',()=>run(async db=>{db.fault=q=>q.name==='sohail_p2_session';const r=await M.call(login,request({user:'Alicia',pass:'prueba123'}));assert.equal(r.status,503);assert.equal(r.body.token,undefined);}));
test('P2 LOGIN invalidated epoch cannot be revived with a stored old password copy',()=>run(async db=>{
 const a=db.tables.sohail_account_security.find(x=>x.id==='g:profile-0');a.pass_hash=await P.hashPassword(GOOD);a.epoch=4;
 assert.equal((await M.call(login,request({user:'Alicia',pass:'prueba123'}))).status,401);
 assert.equal((await M.call(login,request({user:'Alicia',pass:GOOD}))).status,200);
}));

for(const custom of ['tenis',GOOD])for(const actor of ['admin','superadmin'])test('P2 RESET '+actor+' may choose '+(custom==='tenis'?'tenis':'a custom temporary password'),()=>run(async db=>{
 const old=db.token('Alicia'),r=await M.call(password,request({target:'Alicia',newPass:custom},db.token(actor)));
 assert.equal(r.status,200);assert.equal(r.body.passwordTemporary,true);assert.equal(r.body.token,undefined);assert.equal(await L.auth(request({},old)),null);
 const a=db.tables.sohail_account_security.find(x=>x.id==='g:profile-0');assert.ok(P.isModern(a.pass_hash));assert.equal(a.must_change,true);assert.equal(await P.verifyPassword(a.pass_hash,custom),true);
 const entry=await M.call(login,request({user:'Alicia',pass:custom}));assert.equal(entry.status,200);assert.equal(entry.body.mustChangePw,true);
 assert.equal((await M.call(password,request({newPass:SECOND},entry.body.token))).status,200);
 assert.ok(!JSON.stringify(db.tables.audit_log).includes(custom===GOOD?GOOD:'pass_hash'));
}));
test('P2 RESET preserves all passkeys unless explicit revocation selected',()=>run(async db=>{
 db.tables.passkeys=[{credential_id:'pk-a',principal_key:'g:profile-0',user_name:'Alicia'},{credential_id:'pk-b',principal_key:'g:profile-1',user_name:'Beto'}];
 assert.equal((await M.call(password,request({target:'Alicia',newPass:'tenis'},db.token('admin')))).status,200);assert.equal(db.tables.passkeys.length,2);
 assert.equal((await M.call(password,request({target:'Alicia',newPass:'tenis',revokePasskeys:true},db.token('admin')))).status,200);assert.deepEqual(db.tables.passkeys.map(p=>p.credential_id),['pk-b']);
}));
for(const actor of ['Alicia','Beto'])test('P2 RESET player '+actor+' cannot reset somebody else',()=>run(async db=>{const before=JSON.stringify(db.tables.sohail_account_security);const r=await M.call(password,request({target:'Ciro',newPass:'tenis'},db.token(actor)));assert.equal(r.status,403);assert.equal(JSON.stringify(db.tables.sohail_account_security),before);}));
test('P2 RESET delegated administrator cannot reset owner or another administrator',()=>run(async db=>{db.state().users.Alicia.isAdmin=true;db.state().users.Beto.isAdmin=true;for(const target of ['admin','superadmin','Beto'])assert.equal((await M.call(password,request({target,newPass:'tenis'},db.token('Alicia')))).status,403);}));
test('P2 RESET stale administrative verification denies before hashing or mutations',()=>run(async db=>{const token=db.token('admin');await withClock(601000,async()=>{const r=await M.call(password,request({target:'Alicia',newPass:'tenis'},token));assert.equal(r.status,403);assert.equal(r.body.code,'REAUTH_REQUIRED');assert.equal(db.requests.some(q=>q.name==='sohail_p2_change_password'),false);});}));
test('P2 RESET atomic transaction failure preserves credentials and sessions',()=>run(async db=>{const before=JSON.stringify(db.tables);db.fault=q=>q.name==='sohail_p2_change_password';const r=await M.call(password,request({target:'Alicia',newPass:'tenis'},db.token('admin')));assert.equal(r.status,503);assert.equal(JSON.stringify(db.tables),before);}));
test('P2 RESET self-service cannot choose tenis or omit current proof for established account',()=>run(async db=>{for(const data of [{newPass:'tenis',oldPass:'prueba123'},{newPass:GOOD}])assert.equal((await M.call(password,request(data,db.token()))).status,400);}));
test('P2 RESET after committed change, session-creation failure says saved and requires login',()=>run(async db=>{db.fault=q=>q.name==='sohail_p2_session'&&q.body?.p_action==='create';const r=await M.call(password,request({oldPass:'prueba123',newPass:GOOD},db.token()));assert.equal(r.status,200);assert.equal(r.body.ok,true);assert.equal(r.body.requiresLogin,true);assert.equal(await P.verifyPassword(db.tables.sohail_account_security.find(a=>a.id==='g:profile-0').pass_hash,GOOD),true);}));

test('P2 SESSION logout revokes a copied token at server, not merely the cookie',()=>run(async db=>{const token=db.token();assert.ok(await L.auth(request({},token)));const r=await M.call(login,request({accion:'session-logout'},token,{cookie:S.COOKIE+'='+token}));assert.equal(r.status,200);assert.equal(await L.auth(request({},token)),null);assert.ok(cookie(r).includes(S.COOKIE+'='));}));
test('P2 SESSION logout of one device leaves an independent session usable',()=>run(async db=>{const a=db.token(),b=db.newToken();await M.call(login,request({accion:'session-logout'},a));assert.equal(await L.auth(request({},a)),null);assert.ok(await L.auth(request({},b)));}));
test('P2 SESSION logout revokes both stale bearer and newer cookie copies',()=>run(async db=>{const a=db.token(),b=db.newToken();await M.call(login,request({accion:'session-logout'},a,{cookie:S.COOKIE+'='+b}));assert.equal(await L.auth(request({},a)),null);assert.equal(await L.auth(request({},b)),null);}));
test('P2 SESSION failed server revocation does not clear cookie or report success',()=>run(async db=>{db.fault=q=>q.name==='sohail_p2_session'&&q.body.p_action==='revoke';const r=await M.call(login,request({accion:'session-logout'},db.token()));assert.equal(r.status,503);assert.equal(r.body.ok,undefined);assert.equal(r.headers['Set-Cookie'],undefined);}));
test('P2 SESSION list exposes only own device labels and public identifiers',()=>run(async db=>{const r=await M.call(login,request({accion:'session-list'},db.token()));assert.equal(r.status,200);assert.equal(r.body.sessions.length,1);assert.equal(r.body.sessions[0].current,true);for(const bad of ['pass_hash','session_hash','Alicia','g:profile','User-Agent','"epoch"'])assert.ok(!JSON.stringify(r.body).includes(bad));}));
test('P2 SESSION cannot revoke a foreign public session identifier',()=>run(async db=>{const beto=db.token('Beto'),foreign=db.tables.sohail_auth_sessions.find(x=>x.principal==='g:profile-1').public_id;const r=await M.call(login,request({accion:'session-revoke',id:foreign},db.token()));assert.equal(r.status,200);assert.equal(r.body.revoked,0);assert.ok(await L.auth(request({},beto)));}));
test('P2 SESSION close all revokes all own sessions and preserves others',()=>run(async db=>{const a=db.token(),b=db.newToken(),other=db.token('Beto');const r=await M.call(login,request({accion:'session-logout-all'},a));assert.equal(r.status,200);assert.equal(r.body.signedOut,true);assert.equal(await L.auth(request({},a)),null);assert.equal(await L.auth(request({},b)),null);assert.ok(await L.auth(request({},other)));}));
test('P2 SESSION absolute expiry holds after reading data and choosing league',()=>run(async db=>{const token=db.token(),expiry=L.verifyToken(token).exp;await withClock(23*3600000,async()=>{assert.ok(await L.auth(request({},token)));const r=await M.call(state,{...request({},token),method:'GET',query:{liga:'liga-actual',elegir:'1'}});assert.equal(r.status,200);assert.equal(L.verifyToken(r.body.token).exp,expiry);});await withClock(24*3600000,async()=>assert.equal(await L.auth(request({},token)),null));}));
test('P2 SESSION forged signed freshness is overwritten by ledger state',()=>run(async db=>{const p=L.verifyToken(db.token());await withClock(601000,async()=>{const forged=L.signToken({...p,authAt:Date.now(),r:'superadmin'}),s=await L.auth(request({},forged));assert.equal(s.r,'player');assert.throws(()=>A.ensureFresh(s),e=>e.code==='REAUTH_REQUIRED');});}));
for(const change of [s=>delete s.sid,s=>s.sid='short',s=>s.typ='webauthn',s=>s.exp=s.iat+48*3600000,s=>s.iat+=1])test('P2 SESSION rejects malformed or unregistered session contract '+String(change),()=>run(async db=>{const p=L.verifyToken(db.token());change(p);assert.equal(await L.auth(request({},L.signToken(p))),null);}));
test('P2 SESSION no fallback to unsigned/legacy tokens when ledger unavailable',()=>run(async db=>{db.fault=q=>q.name==='sohail_p2_session';await assert.rejects(L.auth(request({},db.token())),e=>e.status===503);}));

test('P2 REAUTH password rotates session and retains original absolute lifetime',()=>run(async db=>{const old=db.token(),initial=L.verifyToken(old);await withClock(601000,async()=>{const r=await M.call(login,request({accion:'session-reauth',pass:'prueba123'},old));assert.equal(r.status,200);const p=L.verifyToken(r.body.token);assert.notEqual(p.sid,initial.sid);assert.equal(p.exp,initial.exp);assert.equal(await L.auth(request({},old)),null);assert.doesNotThrow(()=>A.ensureFresh(p));});}));
test('P2 REAUTH wrong current password is rate-limited and cannot rotate session',()=>run(async db=>{const token=db.token();for(let i=0;i<5;i++){const r=await M.call(login,request({accion:'session-reauth',pass:'incorrecta'},token));assert.equal(r.status,401);assert.equal(r.body.token,undefined);}const r=await M.call(login,request({accion:'session-reauth',pass:'prueba123'},token));assert.equal(r.status,429);assert.ok(await L.auth(request({},token)));}));
test('P2 REAUTH cross-origin credential verification is refused',()=>run(async db=>{const r=await M.call(login,request({accion:'session-reauth',pass:'prueba123'},db.token(),{origin:'https://other.test'}));assert.equal(r.status,403);}));
test('P2 REAUTH verified admin can then perform a chosen temporary reset',()=>run(async db=>{const token=db.token('admin');await withClock(601000,async()=>{const r=await M.call(login,request({accion:'session-reauth',pass:'prueba123'},token));assert.equal(r.status,200);assert.equal((await M.call(password,request({target:'Alicia',newPass:GOOD},r.body.token))).status,200);});}));
test('P2 REAUTH restored signed cookie does not count as a fresh proof',()=>run(async db=>{const token=db.token('admin');await withClock(601000,async()=>{const r=await M.call(login,request({accion:'session-resume'},'',{cookie:S.COOKIE+'='+token}));assert.equal(r.status,200);assert.equal((await M.call(password,request({target:'Alicia',newPass:'tenis'},r.body.token))).body.code,'REAUTH_REQUIRED');});}));
test('P2 REAUTH sensitive role changes need freshness; ordinary profile updates do not',()=>run(async db=>{const token=db.token('admin');await withClock(601000,async()=>{const role=structuredClone(db.state());role.users.Beto.isAdmin=true;const r=await M.call(save,request({state:role,ligaId:'liga-actual'},token));assert.equal(r.body.code,'REAUTH_REQUIRED');assert.equal(db.state().users.Beto.isAdmin,undefined);const s=structuredClone(db.state());s.LEAGUE_NAME='Otro nombre';assert.equal((await M.call(save,request({state:s,ligaId:'liga-actual'},token))).status,200);});}));

const verifiedSpy={generateAuthenticationOptions:async()=>({challenge:'TEST-CHALLENGE'}),generateRegistrationOptions:async()=>({challenge:'TEST-REG'}),verifyAuthenticationResponse:async()=>({verified:true,authenticationInfo:{newCounter:0}}),verifyRegistrationResponse:async()=>({verified:true,registrationInfo:{credential:{id:'credential-1234567890',publicKey:Buffer.from('PUBLIC-TEST'),counter:0}}})};
function existingKey(db,who='Alicia'){const key={credential_id:'credential-1234567890',user_name:who,principal_key:L.principalKey(who,db.state().users[who]),public_key:'AA',counter:0};db.tables.passkeys.push(key);return key;}
test('P2 PASSKEY existing bound credential works; replay of the same challenge is rejected',()=>run(async db=>{existingKey(db);const h=spyPasskey(verifiedSpy),start=await M.call(h,request({accion:'auth-start'})),q=request({accion:'auth-finish',cred:{id:'credential-1234567890'}},'',{cookie:cookie(start)});assert.equal((await M.call(h,q)).status,200);assert.equal((await M.call(h,q)).status,400);}));
test('P2 PASSKEY password reset blocks device login until temporary password is changed',()=>run(async db=>{existingKey(db);asTemporary(db);const h=spyPasskey(verifiedSpy),start=await M.call(h,request({accion:'auth-start'}));const r=await M.call(h,request({accion:'auth-finish',cred:{id:'credential-1234567890'}},'',{cookie:cookie(start)}));assert.equal(r.status,403);assert.equal(r.body.code,'TEMPORARY_PASSWORD_LOGIN');assert.equal(db.tables.passkeys.length,1);}));
test('P2 PASSKEY ambiguous/unbound old credentials do not guess an identity',()=>run(async db=>{existingKey(db).principal_key=null;const h=spyPasskey(verifiedSpy),start=await M.call(h,request({accion:'auth-start'}));assert.equal((await M.call(h,request({accion:'auth-finish',cred:{id:'credential-1234567890'}},'',{cookie:cookie(start)}))).status,401);}));
test('P2 PASSKEY challenge signatures cannot be used as ordinary bearer tokens',()=>run(async db=>{const h=spyPasskey(verifiedSpy),start=await M.call(h,request({accion:'reg-start'},db.token()));const value=cookie(start).split('=')[1];assert.equal(L.verifyToken(value),null);assert.equal(await L.auth(request({},value)),null);}));
test('P2 PASSKEY reauthentication is bound to the same session and account',()=>run(async db=>{existingKey(db);const h=spyPasskey(verifiedSpy),old=db.token(),start=await M.call(h,request({accion:'reauth-start'},old));const r=await M.call(h,request({accion:'reauth-finish',cred:{id:'credential-1234567890'}},old,{cookie:cookie(start)}));assert.equal(r.status,200);assert.equal(L.verifyToken(r.body.token).exp,L.verifyToken(old).exp);assert.equal(await L.auth(request({},old)),null);}));
test('P2 PASSKEY reauth rejects another same-account session’s challenge',()=>run(async db=>{existingKey(db);const h=spyPasskey(verifiedSpy),start=await M.call(h,request({accion:'reauth-start'},db.token()));const r=await M.call(h,request({accion:'reauth-finish',cred:{id:'credential-1234567890'}},db.newToken(),{cookie:cookie(start)}));assert.equal(r.status,400);}));
test('P2 PASSKEY registration challenge cannot be used twice or rebind an existing credential',()=>run(async db=>{const h=spyPasskey(verifiedSpy),token=db.token(),start=await M.call(h,request({accion:'reg-start'},token)),q=request({accion:'reg-finish',cred:{}},token,{cookie:cookie(start)});assert.equal((await M.call(h,q)).status,200);assert.equal((await M.call(h,q)).status,400);assert.equal(db.tables.passkeys[0].principal_key,'g:profile-0');const b=await M.call(h,request({accion:'reg-start'},db.token('Beto')));assert.equal((await M.call(h,request({accion:'reg-finish',cred:{}},db.token('Beto'),{cookie:cookie(b)}))).status,409);assert.equal(db.tables.passkeys[0].principal_key,'g:profile-0');}));
test('P2 PASSKEY administrative deletion needs freshness',()=>run(async db=>{existingKey(db);const token=db.token('admin');await withClock(601000,async()=>{const r=await M.call(spyPasskey(verifiedSpy),request({accion:'admin-delete-user',userName:'Alicia',credentialId:'credential-1234567890'},token));assert.equal(r.body.code,'REAUTH_REQUIRED');assert.equal(db.tables.passkeys.length,1);});}));
test('P2 PASSKEY one same-name user cannot list another principal’s devices',()=>run(async db=>{existingKey(db).principal_key='g:OTHER';const r=await M.call(spyPasskey(verifiedSpy),request({accion:'list'},db.token()));assert.equal(r.status,200);assert.equal(r.body.passkeys.length,0);}));

test('P2 PASSKEY concurrent session revocation prevents registration commit',()=>run(async db=>{
 const token=db.token(),spy={...verifiedSpy,verifyRegistrationResponse:async()=>{db.tables.sohail_auth_sessions.forEach(s=>s.revoked_at=new Date().toISOString());return verifiedSpy.verifyRegistrationResponse();}},h=spyPasskey(spy),start=await M.call(h,request({accion:'reg-start'},token));
 const r=await M.call(h,request({accion:'reg-finish',cred:{}},token,{cookie:cookie(start)}));assert.equal(r.status,409);assert.equal(db.tables.passkeys.length,0);
}));
test('P2 PASSKEY concurrent password reset prevents registration commit',()=>run(async db=>{
 const token=db.token(),spy={...verifiedSpy,verifyRegistrationResponse:async()=>{db.tables.sohail_account_security.find(a=>a.id==='g:profile-0').epoch++;return verifiedSpy.verifyRegistrationResponse();}},h=spyPasskey(spy),start=await M.call(h,request({accion:'reg-start'},token));
 assert.equal((await M.call(h,request({accion:'reg-finish',cred:{}},token,{cookie:cookie(start)}))).status,409);assert.equal(db.tables.passkeys.length,0);
}));
test('P2 PASSKEY deleted credential cannot create a session after verification',()=>run(async db=>{
 existingKey(db);const spy={...verifiedSpy,verifyAuthenticationResponse:async()=>{db.tables.passkeys=[];return verifiedSpy.verifyAuthenticationResponse();}},h=spyPasskey(spy),start=await M.call(h,request({accion:'auth-start'}));
 assert.equal((await M.call(h,request({accion:'auth-finish',cred:{id:'credential-1234567890'}},'',{cookie:cookie(start)}))).status,409);
}));
test('P2 PASSKEY counter cannot move backwards under competing ceremonies',()=>run(async db=>{
 existingKey(db).counter=4;const r=await L.rpc('sohail_p2_passkey',{p_action:'counter',p_data:{credential_id:'credential-1234567890',principal_key:'g:profile-0',expected:4,counter:5}});assert.equal(r.ok,true);
 const stale=await L.rpc('sohail_p2_passkey',{p_action:'counter',p_data:{credential_id:'credential-1234567890',principal_key:'g:profile-0',expected:4,counter:6}});assert.equal(stale.ok,false);assert.equal(db.tables.passkeys[0].counter,5);
}));
