'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {guard}=require('../public/security-account');
const session=require('../public/session-client');
const root=path.join(__dirname,'..');
function fixture(options={}){
 let token='OLD',ctx='liga|account',calls=[],proofs=0;
 const wrap=guard({origin:'https://sohail.test',getToken:()=>token,context:()=>ctx,verify:async()=>{proofs++;if(options.cancel)return false;if(options.switch)ctx='different';token='NEW';return true;},fetcher:async(i,p)=>{calls.push([i,p]);if(options.failure)throw Error('network');return new Response(JSON.stringify(options.body||{code:'REAUTH_REQUIRED'}),{status:options.status||403});}});
 const init={method:'POST',headers:{Authorization:'Bearer OLD'},body:JSON.stringify({accion:'test'})};
 return {wrap,init,calls,proofs:()=>proofs};
}
test('P2 UI guard retries an explicit pre-mutation step-up exactly once',async()=>{const x=fixture();await x.wrap('/api/password',x.init);assert.equal(x.calls.length,2);assert.equal(x.proofs(),1);assert.equal(new Headers(x.calls[1][1].headers).get('Authorization'),'Bearer NEW');assert.equal(x.calls[0][1].body,x.calls[1][1].body);});
for(const url of ['https://other.test/api/password','/api/unknown','/api/users','/api/backup'])test('P2 UI never attaches refreshed tokens to '+url,async()=>{const x=fixture();await x.wrap(url,x.init);assert.equal(x.calls.length,1);assert.equal(x.proofs(),0);});
for(const status of [200,400,401,409,429,500,503])test('P2 UI no automatic retry for status '+status,async()=>{const x=fixture({status});await x.wrap('/api/save',x.init);assert.equal(x.calls.length,1);assert.equal(x.proofs(),0);});
for(const code of ['FORBIDDEN','CREDENTIAL_CONFLICT','SESSION_EXPIRED'])test('P2 UI no automatic retry for error '+code,async()=>{const x=fixture({body:{code}});await x.wrap('/api/password',x.init);assert.equal(x.calls.length,1);assert.equal(x.proofs(),0);});
test('P2 UI cancel does not submit a sensitive mutation',async()=>{const x=fixture({cancel:true});await x.wrap('/api/password',x.init);assert.equal(x.calls.length,1);assert.equal(x.proofs(),1);});
test('P2 UI account/league switch while checking cancels the retry',async()=>{const x=fixture({switch:true});await x.wrap('/api/password',x.init);assert.equal(x.calls.length,1);});
test('P2 UI aborted request does not ask for verification',async()=>{const x=fixture(),a=new AbortController();a.abort();await x.wrap('/api/password',{...x.init,signal:a.signal});assert.equal(x.calls.length,1);assert.equal(x.proofs(),0);});
test('P2 UI transport failures are never retried as password writes',async()=>{const x=fixture({failure:true});await assert.rejects(x.wrap('/api/password',x.init));assert.equal(x.calls.length,1);assert.equal(x.proofs(),0);});
test('P2 UI logout sends a bearer before the app discards it and does not silently succeed on error',async()=>{let init;const c=session.create({getToken:()=> 'CURRENT',fetcher:async(_,i)=>{init=i;return new Response('{}',{status:503});}});const r=await c.logout();assert.equal(init.headers.Authorization,'Bearer CURRENT');assert.equal(init.credentials,'same-origin');assert.equal(r.ok,false);assert.equal(r.code,'LOGOUT_UNCONFIRMED');await assert.rejects(c.beforeLogin(),/LOGOUT_UNCONFIRMED/);});
test('P2 UI unfinished server logout can be retried before a new login',async()=>{let n=0;const c=session.create({fetcher:async()=>new Response(JSON.stringify(++n===1?{}:{ok:true}),{status:n===1?503:200})});assert.equal((await c.logout()).ok,false);await c.beforeLogin();assert.equal(n,2);});
test('P2 UI bundle and stylesheet are explicitly allowlisted',()=>{const m=JSON.parse(fs.readFileSync(path.join(root,'scripts/public-assets.json')));const text=JSON.stringify(m);assert.ok(text.includes('security-account.js'));assert.ok(text.includes('security-account.css'));const html=fs.readFileSync(path.join(root,'public/index.html'),'utf8');assert.ok(html.indexOf('security-account.js')<html.indexOf('bootstrap.js?v='));});
test('P2 SQL migration includes one-use challenges, locked passkey commit, and protected hash format',()=>{const sql=fs.readFileSync(path.join(root,'08_security_part2.sql'),'utf8');assert.match(sql,/CREATE OR REPLACE FUNCTION public.sohail_p2_passkey/);assert.match(sql,/FOR KEY SHARE/);assert.match(sql,/ON CONFLICT\(credential_id\) DO NOTHING/);assert.match(sql,/used_at IS NULL AND expires_at>clock_timestamp/);assert.match(sql,/Credential downgrade prohibited/);assert.doesNotMatch(sql,/DISABLE ROW LEVEL SECURITY|TRUNCATE/i);});
test('P2 native SQL test is manual and cannot reach production credentials',()=>{const w=fs.readFileSync(path.join(root,'.github/workflows/security-part2-db.yml'),'utf8');assert.match(w,/workflow_dispatch/);assert.doesNotMatch(w,/secrets\.|SUPABASE|SESSION_SECRET|VERCEL_TOKEN/);assert.match(w,/contents: read/);for(const f of ['fixture.sql','assertions.sql'])assert.match(fs.readFileSync(path.join(root,'tests/security-db',f),'utf8'),/current_database\(\)<>'sohail_security_test'/);});
test('P2 new dialogs use semantic colors and native labels; no credential browser persistence',()=>{const s=fs.readFileSync(path.join(root,'public/security-account.js'),'utf8'),css=fs.readFileSync(path.join(root,'public/security-account.css'),'utf8');assert.match(s,/type:'password'/);assert.match(s,/autocomplete:'current-password'/);assert.doesNotMatch(s,/localStorage\.setItem|sessionStorage\.setItem|console\.log/);assert.match(css,/var\(--surface/);assert.match(css,/var\(--text/);});
