'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const M=require('./support/mock-db.cjs'),S=require('../api/_session'),C=require('../public/session-client');
const login=require('../api/login'),state=require('../api/state'),password=require('../api/password');
async function run(fn){const prev=global.fetch,db=M.createDB();global.fetch=db.fetch;try{await fn(db);}finally{global.fetch=prev;}}
const request=(body,token='',extra={})=>({method:'POST',query:{},body,headers:{host:'sohail.test',origin:'https://sohail.test','sec-fetch-site':'same-origin','content-type':'application/json','x-sohail-session':'1',...(token?{cookie:S.COOKIE+'='+token}:{}),...extra}});
const signIn=(user='Alicia')=>M.call(login,request({user,pass:'prueba123'}));
for(const name of ['Alicia','admin','superadmin'])test('SESSION460 new login lasts 24 hours and emits protected cookie '+name,()=>run(async db=>{
 const before=Date.now(),r=await signIn(name),after=Date.now(),p=M.lib.verifyToken(r.body.token);assert.equal(r.status,200);assert.equal(M.lib.SESSION_MIN,1440);assert.ok(p.exp>=before+86400000&&p.exp<=after+86400000);
 const cookie=r.headers['Set-Cookie'];for(const part of [S.COOKIE+'=','HttpOnly','Secure','SameSite=Strict','Path=/','Max-Age=86400'])assert.ok(cookie.includes(part),part);assert.ok(!cookie.includes('Domain='));assert.ok(!cookie.includes('pass_hash'));
}));
for(const hours of [2,12,23])test('SESSION460 authenticated resume at '+hours+' hours keeps identity and expiry',()=>run(async db=>{
 const token=(await signIn()).body.token,original=M.lib.verifyToken(token),now=Date.now;
 try{Date.now=()=>now()+hours*3600000;const r=await M.call(login,request({accion:'session-resume'},token));assert.equal(r.status,200);assert.equal(r.body.authenticated,true);assert.equal(r.body.name,'Alicia');assert.equal(r.body.exp,original.exp);assert.equal(M.lib.verifyToken(r.body.token).exp,original.exp);assert.equal(r.body.state.users.Alicia.pass,undefined);assert.equal(r.body.state.users.Beto.email,undefined);}finally{Date.now=now;}
}));
test('SESSION460 expired cookie cannot restore a session and is cleared',()=>run(async db=>{
 const token=db.token(),p=M.lib.verifyToken(token),now=Date.now;try{Date.now=()=>p.exp;const r=await M.call(login,request({accion:'session-resume'},token));assert.equal(r.status,401);assert.ok(r.headers['Set-Cookie'].includes('Max-Age=0'));assert.equal(r.body.state,undefined);}finally{Date.now=now;}
}));
test('SESSION460 altered signed cookie cannot restore privileges',()=>run(async db=>{const tok=db.token(),parts=tok.split('.'),p=JSON.parse(Buffer.from(parts[0],'base64url'));p.r='superadmin';const forged=Buffer.from(JSON.stringify(p)).toString('base64url')+'.'+parts[1];const r=await M.call(login,request({accion:'session-resume'},forged));assert.equal(r.status,401);assert.equal(r.body.token,undefined);}));
test('SESSION460 password/account epoch revocation invalidates saved login',()=>run(async db=>{const token=db.token();db.tables.sohail_account_security.find(x=>x.id==='g:profile-0').epoch++;const r=await M.call(login,request({accion:'session-resume'},token));assert.equal(r.status,401);assert.equal(r.body.state,undefined);}));
test('SESSION460 inactive source profile cannot restore saved login',()=>run(async db=>{const token=db.token();db.state().users.Alicia.inactive=true;assert.equal((await M.call(login,request({accion:'session-resume'},token))).status,401);}));
test('SESSION460 removed or replaced source identity cannot restore another user',()=>run(async db=>{const token=db.token();db.state().users.Alicia.jugadorId='foreign';assert.equal((await M.call(login,request({accion:'session-resume'},token))).status,401);}));
test('SESSION460 current source permissions replace a formerly elevated role',()=>run(async db=>{db.state().users.Alicia.role='admin';const token=db.token();db.state().users.Alicia.role='player';const r=await M.call(login,request({accion:'session-resume'},token));assert.equal(r.body.role,'player');assert.equal(r.body.isAdmin,false);assert.equal(M.lib.verifyToken(r.body.token).r,'player');}));
test('SESSION460 default password restriction survives reload',()=>run(async db=>{db.tables.sohail_account_security.find(x=>x.id==='g:profile-0').must_change=true;const r=await M.call(login,request({accion:'session-resume'},db.token()));assert.equal(r.status,200);assert.equal(r.body.mustChangePw,true);assert.equal(M.lib.verifyToken(r.body.token).m,true);}));
test('SESSION460 source cannot be changed using client name, role or league',()=>run(async db=>{const r=await M.call(login,request({accion:'session-resume',user:'superadmin',role:'superadmin',ligaId:'foreign'},db.token()));assert.equal(r.body.name,'Alicia');assert.equal(r.body.role,'player');assert.equal(r.body.ligaId,'liga-actual');}));
for(const extra of [{'x-sohail-session':''},{'content-type':'text/plain'},{origin:'https://evil.test'},{origin:'http://sohail.test'},{origin:'null'},{'sec-fetch-site':'cross-site'},{'sec-fetch-site':'same-site'}])test('SESSION460 cross-site/form request denied '+JSON.stringify(extra),()=>run(async db=>{const r=await M.call(login,request({accion:'session-resume'},db.token(),extra));assert.equal(r.status,403);assert.equal(r.body.state,undefined);assert.equal(r.body.token,undefined);}));
test('SESSION460 no saved cookie does not query private data or count as failed password',()=>run(async db=>{const r=await M.call(login,request({accion:'session-resume'}));assert.equal(r.status,200);assert.equal(r.body.authenticated,false);assert.equal(db.requests.length,0);}));
test('SESSION460 ordinary private APIs do not accept automatic cookies as authorization',()=>run(async db=>{const r=await M.call(state,{...request({},db.token()),method:'GET',query:{liga:'liga-actual'}});assert.equal(r.status,401);assert.equal(r.body.state,undefined);}));
test('SESSION460 logout clears cookie without modifying league data',()=>run(async db=>{const before=JSON.stringify(db.tables.liga_state),token=db.token();const r=await M.call(login,request({accion:'session-logout'},token));assert.equal(r.status,200);assert.ok(r.headers['Set-Cookie'].includes('Max-Age=0'));assert.equal(JSON.stringify(db.tables.liga_state),before);assert.equal(await M.lib.auth({headers:{authorization:'Bearer '+token}}),null);}));
test('SESSION460 invalid logout origin cannot clear a cookie',()=>run(async db=>{const r=await M.call(login,request({accion:'session-logout'},db.token(),{origin:'https://evil.test'}));assert.equal(r.status,403);assert.equal(r.headers['Set-Cookie'],undefined);}));
test('SESSION460 database failure preserves cookie for retry; no partial authenticated state',()=>run(async db=>{db.fault=q=>q.name==='liga_state';const r=await M.call(login,request({accion:'session-resume'},db.token()));assert.equal(r.status,503);assert.equal(r.headers['Set-Cookie'],undefined);assert.equal(r.body.authenticated,undefined);}));
test('SESSION490 state read keeps absolute expiry and never silently renews',()=>run(async db=>{const token=db.token(),now=Date.now;try{Date.now=()=>now()+13*3600000;const r=await M.call(state,{method:'GET',query:{liga:'liga-actual'},headers:{authorization:'Bearer '+token}});assert.equal(r.status,200);assert.equal(r.body.token,undefined);assert.equal(r.headers['Set-Cookie'],undefined);}finally{Date.now=now;}}));
test('SESSION460 own password change replaces cookie with new epoch; old cookie rejected',()=>run(async db=>{const old=db.token(),q=M.req(db,'Alicia',{ligaId:'liga-actual',oldPass:'prueba123',newPass:'clave-distinta-12345'});const r=await M.call(password,q);assert.equal(r.status,200);assert.ok(r.headers['Set-Cookie'].includes(S.COOKIE));assert.equal((await M.call(login,request({accion:'session-resume'},old))).status,401);assert.equal((await M.call(login,request({accion:'session-resume'},r.body.token))).status,200);}));
test('SESSION460 session cookie preserves existing passkey challenge cookies',()=>run(async db=>{const h=S.withCookie((q,r)=>{r.setHeader('Set-Cookie','pk_auth=x; Max-Age=0');return r.status(200).json({token:db.token()});});const r=await M.call(h,request({}));assert.equal(r.headers['Set-Cookie'].length,2);assert.ok(r.headers['Set-Cookie'][0].startsWith('pk_auth='));assert.ok(r.headers['Set-Cookie'][1].startsWith(S.COOKIE+'='));}));
const memory=()=>{const values=new Map();return {getItem:k=>values.get(k)??null,setItem:(k,v)=>values.set(k,String(v)),removeItem:k=>values.delete(k),values};};
const response=(body,status=200)=>({ok:status<400,status,json:async()=>body});
const good={authenticated:true,token:'secret-access-token',name:'Private Name',ligaId:'league',state:{users:{}}};
test('SESSION460 guest boot does not add a session request before login',async()=>{let called=0;const c=C.create({storage:memory(),fetcher:async()=>called++});assert.equal(await c.restore(),false);assert.equal(called,0);});
test('SESSION460 only non-sensitive boolean hints are stored on login',async()=>{const storage=memory(),c=C.create({storage,fetcher:async()=>response(good)});c.enable();assert.deepEqual([...storage.values],[[C.HINT,'1']]);await c.restore();assert.deepEqual([...storage.values],[[C.HINT,'1']]);});
test('SESSION460 browser reopen uses cookie credentials and accepts verified state once',async()=>{const storage=memory();storage.setItem(C.HINT,'1');let count=0,accepted=0;const c=C.create({storage,fetcher:async(u,o)=>{count++;assert.equal(o.credentials,'same-origin');assert.equal(o.headers['X-Sohail-Session'],'1');assert.equal(o.headers.Authorization,undefined);return response(good);},accept:()=>{accepted++;return true;}});await Promise.all([c.restore(),c.restore()]);assert.equal(count,1);assert.equal(accepted,1);});
test('SESSION460 failed restore does not mount a logged-in app and can retry',async()=>{const storage=memory();storage.setItem(C.HINT,'1');let errors=0,accept=0;const c=C.create({storage,fetcher:async()=>response({},503),accept:()=>accept++,error:()=>errors++});assert.equal(await c.restore(),false);assert.equal(accept,0);assert.equal(errors,1);assert.equal(storage.getItem(C.HINT),'1');});
test('SESSION460 old or absent server cookie removes stale restore hint',async()=>{const storage=memory();storage.setItem(C.HINT,'1');const c=C.create({storage,fetcher:async()=>response({},401)});assert.equal(await c.restore(),false);assert.equal(storage.getItem(C.HINT),null);});
test('SESSION460 logout prevents automatic restore even if network clearing fails',async()=>{const storage=memory();storage.setItem(C.HINT,'1');const c=C.create({storage,fetcher:async()=>{throw Error('offline');}});await c.logout();assert.equal(await c.restore(),false);assert.equal(storage.getItem(C.DISABLED),'1');});
test('SESSION460 response arriving after logout cannot sign user back in',async()=>{let resolve,accepted=0;const storage=memory();storage.setItem(C.HINT,'1');const c=C.create({storage,fetcher:async(u,o)=>JSON.parse(o.body).accion==='session-resume'?new Promise(r=>resolve=r):response({ok:true}),accept:()=>{accepted++;return true;}});const old=c.restore();await c.logout();resolve(response(good));assert.equal(await old,false);assert.equal(accepted,0);});
test('SESSION460 fresh login waits for an outstanding cookie-clear response',async()=>{let resolve,done=false;const c=C.create({storage:memory(),fetcher:()=>new Promise(r=>resolve=r)});c.logout();const p=c.beforeLogin().then(()=>done=true);await Promise.resolve();assert.equal(done,false);resolve(response({ok:true}));await p;assert.equal(done,true);c.enable();});
test('SESSION460 malformed expiry is ignored locally, valid absolute expiry parsed',()=>{assert.equal(C.expiry('garbage'),null);const token=Buffer.from(JSON.stringify({exp:123456})).toString('base64url')+'.signature';assert.equal(C.expiry(token),123456);});
test('SESSION460 both language notes and 24h inactivity are in full shipped files',()=>{const s=fs.readFileSync(path.join(__dirname,'../public/session-client.js'),'utf8'),core=fs.readFileSync(path.join(__dirname,'../public/core-estado.js'),'utf8');assert.ok(s.includes('24 hours'));assert.ok(s.includes('24 horas'));assert.ok(s.includes('shared devices'));assert.match(core,/SESSION_TIMEOUT_MS=24\*60\*60\*1000/);assert.ok(!core.includes("toast('Sesión expirada por inactividad"));});
