'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const R=require('../public/request-task'),Rating=require('../public/rating-client'),H=require('../public/history-leagues'),Session=require('../public/session-client');
const M=require('./support/mock-db.cjs'),route=require('../api/liga');
const response=(data,status=200)=>({ok:status>=200&&status<300,status,headers:{get:()=>null},json:async()=>data});
const pending=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return {promise,resolve,reject};};
const rating=()=>({complete:true,window:50,version:'sohail-rating-4.6.0',snapshot:'a'.repeat(64),info:{},byLeague:{},leagues:[]});
const tick=()=>new Promise(r=>setImmediate(r));

for(const phase of ['headers','body'])test('ST511 deadline covers an uncooperative '+phase+' promise',async()=>{
 let calls=0;const never=()=>new Promise(()=>{});
 await assert.rejects(R.json(async()=>{calls++;return phase==='headers'?never():{ok:true,json:never};},'/test',{method:'GET'},{timeout:8}),e=>e.code==='REQUEST_TIMEOUT');
 assert.equal(calls,1);
});
test('ST511 pre-aborted signal sends no request',async()=>{const ctl=new AbortController();ctl.abort();let calls=0;await assert.rejects(R.json(()=>{calls++;},'/test',{}, {signal:ctl.signal}),e=>e.code==='REQUEST_ABORTED');assert.equal(calls,0);});
test('ST511 cancellation ends even if the transport ignores AbortSignal',async()=>{const wait=pending(),ctl=new AbortController();const p=R.json(()=>wait.promise,'/test',{}, {signal:ctl.signal,timeout:1000});ctl.abort();await assert.rejects(p,e=>e.code==='REQUEST_ABORTED');wait.reject(Error('late failure'));await tick();});
test('ST511 write transport never retries on network error',async()=>{let calls=0;await assert.rejects(R.json(async()=>{calls++;throw Error('connection lost');},'/api/save',{method:'POST'}));assert.equal(calls,1);});
for(const body of [null,[],12,'<html>'])test('ST511 malformed JSON shape is rejected '+JSON.stringify(body),async()=>{await assert.rejects(R.json(async()=>response(body),'/test'),e=>e.code==='REQUEST_INVALID_RESPONSE');});
test('ST511 HTTP denial remains denial with HTML rather than JSON',async()=>{const r=await R.json(async()=>({ok:false,status:401,json:async()=>{throw new SyntaxError('html');}}),'/test');assert.equal(r.response.status,401);assert.deepEqual(r.data,{});});
test('ST511 successful HTTP with invalid JSON is not an acknowledgement',async()=>{await assert.rejects(R.json(async()=>({ok:true,status:200,json:async()=>{throw new SyntaxError('html');}}),'/test'));});
test('ST511 response arriving after timeout cannot repopulate rating',async()=>{const w=pending();const c=Rating.create({getToken:()=>'',fetcher:()=>w.promise,timeout:8});await c.load();assert.equal(c.peek().busy,false);w.resolve(response(rating()));await tick();assert.equal(c.peek().data,null);assert.equal(c.peek().error.code,'REQUEST_TIMEOUT');});
test('ST511 rating body timeout can be retried manually',async()=>{let fail=true;const c=Rating.create({getToken:()=>'',timeout:8,fetcher:async()=>fail?{ok:true,json:()=>new Promise(()=>{})}:response(rating())});assert.equal(await c.load(),null);fail=false;assert.ok(await c.load());assert.equal(c.peek().error,null);});
for(const language of ['es','en'])test('ST511 rating error is localized and never exposes raw exception '+language,async()=>{const c=Rating.create({getToken:()=>'',getLanguage:()=>language,fetcher:async()=>{throw Error('secret-private-raw-url');}});await c.load();assert.ok(!JSON.stringify(c.peek()).includes('secret-private'));assert.match(c.peek().error.message,language==='en'?/could not be verified/:/No se pudo comprobar/);});
test('ST511 malformed numeric rating is rejected before rendering',()=>{const d=rating();d.info.x={ratingCalculado:'oops',prior:8,effectiveMatches:4,partidos:4};assert.equal(Rating.valid(d),false);});
test('ST511 dangling player references cannot reach toFixed rendering',()=>{const d=rating();d.byLeague.test={A:'missing'};assert.equal(Rating.valid(d),false);});
test('ST511 rating 429 does not produce a retry flood',async()=>{let count=0,now=0;const c=Rating.create({clock:()=>now,getToken:()=>'',fetcher:async()=>{count++;return {...response({code:'RATE_LIMIT'},429),headers:{get:()=> '2'}};}});await c.load();await c.load(true);assert.equal(count,1);now=2001;await c.load(true);assert.equal(count,2);});
test('ST511 clear aborts a pending detail read',async()=>{const wait=pending();const c=Rating.create({getToken:()=>'A',fetcher:()=>wait.promise,timeout:1000});const p=c.details('x','s');c.clear();await assert.rejects(p,e=>e.code==='REQUEST_ABORTED');wait.resolve(response({snapshot:'s',selected:[],leagues:[]}));});
test('ST511 session cancellation releases the login busy state',async()=>{const wait=pending(),busy=[];const c=Session.create({storage:null,fetcher:()=>wait.promise,busy:v=>busy.push(v),timeout:1000});const p=c.restore();c.cancel();assert.equal(busy.at(-1),false);assert.equal(await p,false);wait.resolve(response({authenticated:false}));});
test('ST511 session restore stalled in body ends without accepting partial login',async()=>{let accepted=0;const c=Session.create({storage:null,timeout:8,accept:()=>accepted++,fetcher:async()=>({ok:true,json:()=>new Promise(()=>{})})});assert.equal(await c.restore(),false);assert.equal(accepted,0);});
test('ST511 empty successful logout response is explicitly unconfirmed',async()=>{const c=Session.create({storage:null,fetcher:async()=>response({})});assert.equal((await c.logout()).code,'LOGOUT_UNCONFIRMED');await assert.rejects(c.beforeLogin(),/LOGOUT_UNCONFIRMED/);});

function setup(){const a=M.fixture();a.matches=[M.match({id:1,status:'confirmed'})];const b=structuredClone(a);b.matches.push(M.match({id:2,status:'confirmed'}));return M.createDB([{id:'liga-actual',state:a},{id:'past',state:b,estado:'finalizada'}]);}
async function dbTest(fn){const db=setup(),old=global.fetch;global.fetch=db.fetch;H.clearCache();delete require.cache[require.resolve('../api/_rating')];try{return await fn(db);}finally{global.fetch=old;}}
const current=db=>({id:'liga-actual',nombre:'Current',...structuredClone(db.state())});
const bridge=db=>async(url,options)=>{const u=new URL(url,'https://app.invalid');const r=await M.call(route,{method:'POST',query:Object.fromEntries(u.searchParams),headers:Object.fromEntries(Object.entries(options.headers||{}).map(([k,v])=>[k.toLowerCase(),v])),body:JSON.parse(options.body)});return response(r.body,r.status);};
const rq=(db,body)=>M.req(db,'admin',body,{operacion:'rating'});
test('ST511 all-history includes the active season from the server, not an old browser array',()=>dbTest(async db=>{
 const c=current(db);c.matches=[];const h=H.createController({current:()=>c,name:'Alicia',token:()=>db.token(),valid:()=>true,fetcher:bridge(db)});
 assert.equal(await h.load(),true);assert.equal(h.snapshot().records.length,3);assert.equal(h.snapshot().records.filter(m=>m._mhLeagueId==='liga-actual').length,1);
}));
test('ST511 unsaved browser result never inflates global history',()=>dbTest(async db=>{const c=current(db);c.matches.push(M.match({id:300,status:'confirmed'}));const h=H.createController({current:()=>c,name:'Alicia',token:()=>db.token(),valid:()=>true,fetcher:bridge(db)});await h.load();assert.equal(h.snapshot().records.length,3);}));
test('ST511 active-season edit invalidates notModified too',()=>dbTest(async db=>{const c=current(db),opts={current:c,name:'Alicia',token:db.token(),fetcher:bridge(db)};const a=await H.collect(opts);db.state().matches[0].sets=[[6,0],[6,0]];const b=await H.collect(opts);assert.notEqual(a.signature,b.signature);assert.deepEqual(b.records.find(x=>x._mhLeagueId==='liga-actual').sets,[[6,0],[6,0]]);}));
test('ST511 global history never merges identities by name when no link exists',()=>dbTest(async db=>{delete db.state().users.Alicia.jugadorId;const r=await H.collect({current:current(db),name:'Alicia',token:db.token('admin'),fetcher:bridge(db)});assert.equal(r.linked,false);assert.equal(r.records.length,1);assert.equal(r.records[0]._mhLeagueId,'liga-actual');}));
test('ST511 public coherent request cannot add a private current league',()=>dbTest(async db=>{const r=await M.call(route,{method:'POST',headers:{},query:{operacion:'history'},body:{name:'Alicia',id:'profile-0',currentId:'liga-actual',coherent:true}});assert.equal(r.status,403);assert.equal(r.body.records,undefined);}));
test('ST511 legacy history contract remains readable during deployment rollover',()=>dbTest(async db=>{const r=await M.call(route,M.req(db,'admin',{name:'Alicia',id:'profile-0',currentId:'liga-actual'},{operacion:'history'}));assert.equal(r.status,200);assert.equal(r.body.records.length,2);assert.equal(r.body.coherent,undefined);}));
test('ST511 history failure clears ready data instead of falling back',()=>dbTest(async db=>{let fail=false;const f=bridge(db),h=H.createController({current:()=>current(db),name:'Alicia',token:()=>db.token(),valid:()=>true,fetcher:(...args)=>{if(fail)throw Error('network');return f(...args);}});assert.ok(await h.load());fail=true;await h.load();assert.equal(h.snapshot().ready,false);assert.equal(h.snapshot().error,true);assert.equal(h.snapshot().records.length,0);}));
test('ST511 cache metadata from an old backend is rejected explicitly',()=>dbTest(async db=>{await assert.rejects(H.collect({current:current(db),name:'Alicia',token:db.token(),fetcher:async()=>response({complete:true,signature:'a'.repeat(64),records:[],leagues:[],index:[],issues:[]})}),/incomplete-history/);}));
test('ST511 cancelled history request releases its pending state even without native cancellation',()=>dbTest(async db=>{const w=pending(),h=H.createController({current:()=>current(db),name:'Alicia',token:()=>db.token(),valid:()=>true,fetcher:()=>w.promise,timeout:1000});const p=h.load();h.cancel();assert.equal(await p,false);assert.equal(h.snapshot().busy,false);assert.equal(h.snapshot().records.length,0);w.resolve(response({}));}));
test('ST511 history body timeout leaves an explicit retryable failure',()=>dbTest(async db=>{const h=H.createController({current:()=>current(db),name:'Alicia',token:()=>db.token(),valid:()=>true,timeout:8,fetcher:async()=>({ok:true,json:()=>new Promise(()=>{})})});await h.load();assert.equal(h.snapshot().busy,false);assert.equal(h.snapshot().error,true);}));
test('ST511 changed identity during a request cannot populate the next viewer',()=>dbTest(async db=>{let c=current(db);const w=pending(),h=H.createController({current:()=>c,name:'Alicia',token:()=>db.token(),valid:()=>true,fetcher:()=>w.promise,timeout:1000});const p=h.load();c.users.Alicia.historialId='other';h.snapshot();assert.equal(await p,false);w.resolve(response({}));assert.equal(h.snapshot().ready,false);}));
test('ST511 derived-cache write failure still serves a freshly validated complete rating',()=>dbTest(async db=>{const f=global.fetch;global.fetch=(url,op)=>url.endsWith('/sohail_perf_cache_put')?Promise.reject(Error('cache write failed')):f(url,op);const r=await M.call(route,rq(db,{}));assert.equal(r.status,200);assert.equal(r.body.complete,true);assert.equal(r.body.matchCount,3);}));
test('ST511 corrupted derived payload is replaced, not rendered',()=>dbTest(async db=>{await M.call(route,rq(db,{}));delete require.cache[require.resolve('../api/_rating')];db.tables.sohail_derived_cache[0].payload={computed:{info:{}},manifest:[]};const r=await M.call(route,rq(db,{}));assert.equal(r.status,200);assert.equal(r.headers['X-Sohail-Rating-Cache'],'computed');assert.equal(r.body.matchCount,3);}));
test('ST511 failing cache-source read has one full-source fallback only',()=>dbTest(async db=>{const f=global.fetch;let attempts=0;global.fetch=(url,op)=>{if(url.endsWith('/sohail_perf_source')){attempts++;if(JSON.parse(op.body).p_model)throw Error('cache join failed');}return f(url,op);};const r=await M.call(route,rq(db,{}));assert.equal(r.status,200);assert.equal(attempts,2);}));
test('ST511 failed authoritative source never returns cached successful data',()=>dbTest(async db=>{await M.call(route,rq(db,{}));db.fault=q=>q.name==='sohail_perf_source';const r=await M.call(route,rq(db,{}));assert.equal(r.status,503);assert.equal(r.body.complete,undefined);}));
test('ST511 optional cache bypass retains full scope and security',()=>dbTest(async db=>{const previous=process.env.SOHAIL_RATING_CACHE_DISABLED;process.env.SOHAIL_RATING_CACHE_DISABLED='1';try{const r=await M.call(route,rq(db,{}));assert.equal(r.status,200);assert.equal(r.body.matchCount,3);assert.equal(db.tables.sohail_derived_cache.length,0);const q=rq(db,{});db.tables.sohail_auth_sessions.forEach(s=>s.revoked_at=new Date().toISOString());assert.equal((await M.call(route,q)).status,401);}finally{if(previous===undefined)delete process.env.SOHAIL_RATING_CACHE_DISABLED;else process.env.SOHAIL_RATING_CACHE_DISABLED=previous;}}));

function persistence(fetcher,timeout){
 const base=M.fixture(),notes=[];const ctx={JSON,Promise,Blob,structuredClone,AbortController,AbortSignal,LANG:'es',console:{log(){},warn(){},error(){}},fetch:fetcher,
  SohailRequest:timeout?{...R,json:(a,b,c,d)=>R.json(a,b,c,{...d,timeout})}:R,setTimeout:()=>0,setInterval:()=>0,clearTimeout(){},atob:s=>Buffer.from(s,'base64').toString(),t:k=>k,
  window:{addEventListener(){},dispatchEvent(){}},Event,document:{getElementById:()=>null,addEventListener(){},createElement:()=>({style:{},appendChild(){},setAttribute(){}}),body:{appendChild(){}}},
  _conLiga:u=>u,currentUser:{name:'Alicia'},_token:'T',_ligaActual:'liga-actual',_ligaReadOnly:false,RATING_ON:false,cycles:base.cycles,matches:[],matchId:1,activeN:1,playoff:base.playoff,
  DESTINO:{},FECHAS:{},PO_FECHAS:{},ALLNAMES:base.ALLNAMES,USERS:base.users,PUNTOS:{},AJUSTES_PUNTOS:{},LOG:[],LEAGUE_NAME:'Synthetic',LEAGUE_SUBTITLE:'',LOGIN_TITLE:'',LEAGUE_COLOR_PRI:'#123456',LEAGUE_COLOR_ACC:'#123456',LEAGUE_COLOR_HL:'#123456',LEAGUE_TEXT_COLORS:{},CLUBS:base.CLUBS,COLOR_DISPUTA:'#123456',RATING_SEEDS:{},RATING_OVERRIDES:{},REGLAMENTO:'',LOGIN_HEADER:{},JOIN_REQUESTS:[],notes,applied:[]};
 vm.createContext(ctx);vm.runInContext(fs.readFileSync(path.join(__dirname,'../public/persistencia.js'),'utf8'),ctx);
 vm.runInContext('_loadOK=true;_stateV=3;_lastSaved=_serialize();_showLoadError=x=>notes.push(x);_hideLoadError=()=>{};_hydrate=d=>{applied.push(d._v);_stateV=d._v;return true;}',ctx);
 return {ctx,run:s=>vm.runInContext(s,ctx),notes};
}
for(const data of [{},{ok:false,version:4},{ok:true},{ok:true,version:'4'},{ok:true,version:3}])test('ST511 malformed save acknowledgement pauses automatic writes '+JSON.stringify(data),async()=>{let calls=0;const x=persistence(async()=>{calls++;return response(data);});x.run("LEAGUE_NAME='Edited'");assert.equal(await x.run('persist(true)'),false);assert.equal(await x.run('persist(true)'),false);assert.equal(calls,1);assert.equal(x.run('_stateV'),3);assert.equal(x.run('_saveUnconfirmed'),true);assert.equal(x.run('_serialize()===_lastSaved'),false);});
test('ST511 ambiguous save timeout is not automatically repeated',async()=>{let calls=0;const x=persistence(async()=>{calls++;return {ok:true,json:()=>new Promise(()=>{})};},8);assert.equal(await x.run('_doPersist()'),false);assert.equal(await x.run('_doPersist()'),false);assert.equal(calls,1);assert.equal(x.run('_saveInFlight'),null);});
test('ST511 exact save acknowledgement advances version normally',async()=>{const x=persistence(async()=>response({ok:true,version:4}));assert.equal(await x.run('_doPersist()'),true);assert.equal(x.run('_stateV'),4);assert.equal(x.run('_saveUnconfirmed'),false);});
test('ST511 older results response cannot replace the newest response',async()=>{const a=pending(),b=pending();let n=0;const x=persistence(()=>++n===1?a.promise:b.promise);const pa=x.run('loadState()'),pb=x.run('loadState()');b.resolve(response({state:{...M.fixture(),_v:9}}));await pb;a.resolve(response({state:{...M.fixture(),_v:4}}));await pa;assert.deepEqual(x.ctx.applied,[9]);});
test('ST511 a changed token rejects the late state response even for same account',async()=>{const w=pending(),x=persistence(()=>w.promise);const p=x.run('loadState()');x.ctx._token='OTHER';w.resolve(response({state:{...M.fixture(),_v:4}}));await p;assert.deepEqual(x.ctx.applied,[]);});
test('ST511 state timeout blocks unsafe autosave and can retry',async()=>{let hang=true;const x=persistence(async()=>hang?{ok:true,json:()=>new Promise(()=>{})}:response({state:{...M.fixture(),_v:4}}),8);await x.run('loadState()');assert.equal(x.run('_loadOK'),false);hang=false;assert.equal(await x.run('loadState()'),true);assert.equal(x.run('_loadOK'),true);});
test('ST511 late write error in former league cannot pause the new league',async()=>{const w=pending(),x=persistence(()=>w.promise);const p=x.run('_doPersist()');x.ctx._ligaActual='another';w.reject(Error('late'));await p;assert.equal(x.run('_saveUnconfirmed'),false);});
test('ST511 failed hydration never leaves autosave enabled',async()=>{const x=persistence(async()=>response({state:{...M.fixture(),_v:4}}));x.run('_hydrate=()=>false');await x.run('loadState()');assert.equal(x.run('_loadOK'),false);});
for(const failure of ['language','session','login'])test('ST511 startup failure is contained at '+failure,async()=>{let login=0;const el={style:{}};const ctx={window:{SohailSession:{restore:async()=>{if(failure==='session')throw Error('failed');return false;}}},document:{documentElement:{lang:'es'},getElementById:()=>el},updateLangUI:()=>{if(failure==='language')throw Error('failed');},initLogin:async()=>{login++;if(failure==='login')throw Error('failed');},SohailSession:null};ctx.SohailSession=ctx.window.SohailSession;vm.createContext(ctx);vm.runInContext(fs.readFileSync(path.join(__dirname,'../public/bootstrap.js'),'utf8'),ctx);await tick();assert.equal(login,1);assert.equal(el.style.display,'block');});
test('ST511 shipped request helper is explicitly allowlisted and loaded before clients',()=>{const root=path.resolve(__dirname,'..'),html=fs.readFileSync(path.join(root,'public/index.html'),'utf8'),assets=JSON.parse(fs.readFileSync(path.join(root,'scripts/public-assets.json')));assert.ok(assets.assets.includes('request-task.js'));for(const f of ['history-leagues.js','session-client.js','rating-client.js','bootstrap.js'])assert.ok(html.indexOf('request-task.js')<html.indexOf(f));});

for(const value of [null,[],{},'bad',{_v:2},{_v:2,users:[],matches:[],cycles:[]}])test('ST511 incomplete state never enables autosave '+JSON.stringify(value),async()=>{const x=persistence(async()=>response({state:value}));await x.run('loadState()');assert.equal(x.run('_loadOK'),false);assert.deepEqual(x.ctx.applied,[]);});
test('ST511 valid minimal state envelope passes guard',()=>assert.equal(R.stateValid(M.fixture()),true));
test('ST511 pending changes survive a failed read and retain unload warning',async()=>{const x=persistence(async()=>{throw Error('offline');});x.run("LEAGUE_SUBTITLE='pending'");await x.run('loadState()');assert.equal(x.run('_loadOK'),false);assert.equal(x.run('_hasPendingChanges()'),true);assert.match(fs.readFileSync(path.join(__dirname,'../public/persistencia.js'),'utf8'),/beforeunload[^\n]+if\(_token&&!_ligaReadOnly/);});
test('ST511 synchronous cancellation/throw has no orphaned rejection',async()=>{const ctl=new AbortController();await assert.rejects(R.run(()=>{ctl.abort();throw Error('sync failed');},{signal:ctl.signal,timeout:50}));await tick();});
for(const d of [null,{}, {token:'t',name:'A',role:'stranger'}, {token:'t',name:'A',role:'player',ligaId:'liga-actual',state:{}}, {token:'t',name:'A',role:'player',eligeLiga:true,ligas:[]}])test('ST511 malformed login metadata cannot mount authenticated UI '+JSON.stringify(d),()=>{const text=fs.readFileSync(path.join(__dirname,'../public/login-auth-p2.js'),'utf8'),part=text.slice(text.indexOf('function loginResponseValid('),text.indexOf('async function doLogin(')),ctx={SohailRequest:R,d};vm.createContext(ctx);vm.runInContext(part,ctx);assert.equal(vm.runInContext('loginResponseValid(d)',ctx),false);});

test('ST511 coherent history rejects identity changed since the page opened',()=>dbTest(async db=>{db.state().users.Alicia.historialId='new-sporting-person';const request=M.req(db,'Alicia',{currentId:'liga-actual',name:'Alicia',id:'profile-0',coherent:true},{operacion:'history'});const r=await M.call(route,request);assert.equal(r.status,409);assert.equal(r.body.code,'HISTORY_IDENTITY_CHANGED');assert.equal(r.body.records,undefined);}));
test('ST511 corrupt cached rating numbers trigger authoritative recalculation',()=>dbTest(async db=>{await M.call(route,rq(db,{}));delete require.cache[require.resolve('../api/_rating')];const p=db.tables.sohail_derived_cache[0].payload;Object.values(p.computed.info)[0].partidos='invalid';const r=await M.call(route,rq(db,{}));assert.equal(r.status,200);assert.equal(r.headers['X-Sohail-Rating-Cache'],'computed');assert.ok(Object.values(r.body.info).every(v=>Number.isInteger(v.partidos)));}));

test('ST511 unconfirmed outbound snapshot survives a local editor rollback',async()=>{const x=persistence(async()=>response({}));x.run("LEAGUE_SUBTITLE='Attempted edit'");await x.run('_doPersist()');x.run("LEAGUE_SUBTITLE=''");assert.equal(x.run('_serialize()===_lastSaved'),true);assert.equal(x.run('_unconfirmedAttempt.LEAGUE_SUBTITLE'),'Attempted edit');assert.equal(x.run('_hasPendingChanges()'),true);assert.match(fs.readFileSync(path.join(__dirname,'../public/persistencia.js'),'utf8'),/sentUnconfirmed:_unconfirmedAttempt/);});
test('ST511 nonboolean league-choice flag is rejected',()=>{const text=fs.readFileSync(path.join(__dirname,'../public/login-auth-p2.js'),'utf8'),part=text.slice(text.indexOf('function loginResponseValid('),text.indexOf('async function doLogin(')),ctx={SohailRequest:R,d:{token:'t',name:'Alicia',role:'player',ligaId:'liga-actual',state:M.fixture(),eligeLiga:'yes'}};vm.createContext(ctx);vm.runInContext(part,ctx);assert.equal(vm.runInContext('loginResponseValid(d)',ctx),false);});

test('ST511 previous session of the same account cannot acknowledge a new session write',async()=>{const w=pending(),x=persistence(()=>w.promise),token=sid=>Buffer.from(JSON.stringify({u:'Alicia',pk:'g:profile-0',sv:0,sid})).toString('base64url')+'.signed';x.ctx._token=token('old');const p=x.run('_doPersist()');x.ctx._token=token('new');w.resolve(response({ok:true,version:4}));assert.equal(await p,false);assert.equal(x.run('_stateV'),3);assert.equal(x.run('_saveUnconfirmed'),false);});
